# Connection: 200.0.0.227
# Host: 200.0.0.227
# Saved: 2017-03-18 16:57:32
# 
SELECT RIGHT(100000+H.INVOICE_SR_NO,5) AS TAX_INVOICE,H.INVOICE_NO,P.PARTY_NAME,P.ADDRESS1,P.ADDRESS2,P.PINCODE,P.TIN_NO,P.TIN_DATE,H.GATEPASS_NO,P.DOCUMENT_THROUGH,H.INV_NO,H.INVOICE_DATE,H.PACKING_DATE,H.PARTY_CODE,M.PARTY_NAME AS AGENT_NAME,H.SALE_NOTE_NO,CONCAT((H.BANK_CHARGES*1),(H.TRANSPORT_MODE*1)) AS CHARGE_CD,H.BALE_NO,H.STATION_CODE,H.TRANSPORTER_NAME,D.DESCRIPTION,D.QUALITY_CD,D.WIDTH,D.GROSS_SQ_MTR,D.PIECE_NO,D.GROSS_QTY,D.NET_QTY,D.FLAG_DEF_CODE,D.NET_QTY,D.GROSS_AMOUNT,D.RATE,D.NET_AMOUNT,D.EXCISABLE_VALUE,H.TOTAL_SQ_MTR,H.TOTAL_KG,H.TOTAL_GROSS_QTY,H.TOTAL_NET_QTY,H.TOTAL_NET_AMOUNT,H.EXCISABLE_VALUE,CASE WHEN H.VAT4>0 THEN 'VAT 4%' WHEN H.CST2>0 THEN 'CST 2%' ELSE 'CST 5%' END AS TAX_LABEL1,CASE WHEN H.VAT1>0 THEN 'VAT 1%' ELSE '' END AS TAX_LABEL2,CASE WHEN H.VAT4>0 THEN H.VAT4 WHEN H.CST2>0 THEN H.CST2 ELSE H.CST5 END AS TAX_VAL1,CASE WHEN H.VAT1>0 THEN H.VAT1 ELSE 0 END AS TAX_VAL2,H.INSURANCE_CHARGES,H.TOTAL_VALUE,H.NET_AMOUNT
FROM FILTERFABRIC.FF_TRD_INVOICE_HEADER H,FILTERFABRIC.FF_TRD_INVOICE_DETAIL D,DINESHMILLS.D_SAL_PARTY_MASTER P
LEFT JOIN (SELECT PARTY_CODE,PARTY_NAME FROM DINESHMILLS.D_SAL_PARTY_MASTER WHERE MAIN_ACCOUNT_CODE=210072) M
ON M.PARTY_CODE=CONCAT(LEFT(P.PARTY_CODE,2),'0000') 
WHERE H.INVOICE_NO=D.INVOICE_NO AND H.INVOICE_DATE=D.INVOICE_DATE AND H.LOT_NO=D.LOT_NO AND H.PARTY_CODE=P.PARTY_CODE
AND P.MAIN_ACCOUNT_CODE=210072 