# Connection: 200.0.0.227
# Host: 200.0.0.227
# Saved: 2017-03-21 18:11:31
# 
SELECT A.*,B.*,C.*,PARTY_NAME FROM 
((SELECT MIN(INVOICE_NO) AS INVMIN,MAX(INVOICE_NO) AS INVMAX,(MAX(INVOICE_NO)-MIN(INVOICE_NO))+1 AS INVTOT FROM FF_TRD_INVOICE_HEADER) AS A,
(SELECT LEFT(PARTY_CODE,2) AS AGENT,MIN(AGENT_SR_NO) AS AGNTMIN,MAX(AGENT_SR_NO) AS AGNTMAX,(MAX(AGENT_SR_NO)-MIN(AGENT_SR_NO))+1 AS AGNTTOT FROM FF_TRD_INVOICE_HEADER
GROUP BY AGENT_ALPHA) AS B,
(SELECT MIN(GATEPASS_NO) AS GPMIN,MAX(GATEPASS_NO) AS GPMAX,(MAX(GATEPASS_NO)-MIN(GATEPASS_NO))+1 AS GPTOT FROM FF_TRD_INVOICE_HEADER) AS C
)
LEFT JOIN DINESHMILLS.D_SAL_PARTY_MASTER D
ON D.PARTY_CODE=CONCAT(AGENT,'0000')
WHERE MAIN_ACCOUNT_CODE=210072


