/*
 * frmGRNFind.java
 *
 * Created on May 15, 2004, 1:35 PM
 */

package EITLERP.Finance;

/**
 *
 * @author  nrpithva
 */  
 
/*<APPLET CODE=frmGRNFind.class HEIGHT=405 WIDTH=565></APPLET>*/

import javax.swing.*;
import java.awt.*;
import java.util.*;
import EITLERP.*;
 

public class frmOBCInvoiceFind extends javax.swing.JApplet {
    
    private EITLComboModel cmbStatusModel;

    public boolean Cancelled=false;
    public String strQuery;
    public int GRNType=2;

    private EITLComboModel cmbForDeptModel;
    private EITLComboModel cmbBuyerModel;
    
    /** Initializes the applet frmGRNFind */
    public void init() {
        System.gc();
        setSize(565,380);
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        cmdFind = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblMainCode = new javax.swing.JLabel();
        txtMainCode = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPartyCode = new javax.swing.JLabel();
        txtPartyCode = new javax.swing.JTextField();
        lblInvoiceNo = new javax.swing.JLabel();
        lblInvoiceDate = new javax.swing.JLabel();
        txtInvoiceDate = new javax.swing.JTextField();
        txtInvoiceNo = new javax.swing.JTextField();
        lblDocNo = new javax.swing.JLabel();
        txtDocNo = new javax.swing.JTextField();
        lblDocNo1 = new javax.swing.JLabel();
        txtDocFrom = new javax.swing.JTextField();
        lblDocNo2 = new javax.swing.JLabel();
        txtDocTo = new javax.swing.JTextField();
        lblAccountID2 = new javax.swing.JLabel();
        txtBankRefNo = new javax.swing.JTextField();
        lblDocNo3 = new javax.swing.JLabel();
        txtBankFrom = new javax.swing.JTextField();
        lblDocNo4 = new javax.swing.JLabel();
        txtBankTo = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Find Records");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 12, 170, 15);

        cmdFind.setText("Find");
        cmdFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdFind.setNextFocusableComponent(cmdCancel);
        cmdFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindActionPerformed(evt);
            }
        });

        getContentPane().add(cmdFind);
        cmdFind.setBounds(482, 40, 70, 25);

        cmdCancel.setText("Cancel");
        cmdCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCancel.setNextFocusableComponent(cmdClear);
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        getContentPane().add(cmdCancel);
        cmdCancel.setBounds(482, 70, 70, 25);

        cmdClear.setText("Clear");
        cmdClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdClear.setNextFocusableComponent(txtMainCode);
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        getContentPane().add(cmdClear);
        cmdClear.setBounds(482, 110, 70, 25);

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblMainCode.setDisplayedMnemonic('G');
        lblMainCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMainCode.setLabelFor(txtMainCode);
        lblMainCode.setText("Main Code :");
        jPanel1.add(lblMainCode);
        lblMainCode.setBounds(10, 190, 110, 15);

        txtMainCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMainCodeFocusLost(evt);
            }
        });
        txtMainCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMainCodeKeyPressed(evt);
            }
        });

        jPanel1.add(txtMainCode);
        txtMainCode.setBounds(130, 190, 110, 20);

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name :");
        jPanel1.add(lblName);
        lblName.setBounds(10, 220, 110, 15);

        txtName.setEditable(false);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        jPanel1.add(txtName);
        txtName.setBounds(130, 220, 320, 20);

        lblPartyCode.setDisplayedMnemonic('G');
        lblPartyCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPartyCode.setLabelFor(txtMainCode);
        lblPartyCode.setText("Party Code :");
        jPanel1.add(lblPartyCode);
        lblPartyCode.setBounds(10, 105, 110, 15);

        jPanel1.add(txtPartyCode);
        txtPartyCode.setBounds(130, 105, 110, 20);

        lblInvoiceNo.setDisplayedMnemonic('G');
        lblInvoiceNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInvoiceNo.setLabelFor(txtMainCode);
        lblInvoiceNo.setText("Invoice No :");
        jPanel1.add(lblInvoiceNo);
        lblInvoiceNo.setBounds(10, 80, 110, 15);

        lblInvoiceDate.setDisplayedMnemonic('G');
        lblInvoiceDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInvoiceDate.setLabelFor(txtMainCode);
        lblInvoiceDate.setText("Inv Date :");
        jPanel1.add(lblInvoiceDate);
        lblInvoiceDate.setBounds(250, 80, 65, 15);

        jPanel1.add(txtInvoiceDate);
        txtInvoiceDate.setBounds(320, 80, 110, 20);

        jPanel1.add(txtInvoiceNo);
        txtInvoiceNo.setBounds(130, 80, 110, 20);

        lblDocNo.setDisplayedMnemonic('G');
        lblDocNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocNo.setText("Doc No :");
        jPanel1.add(lblDocNo);
        lblDocNo.setBounds(10, 20, 110, 15);

        jPanel1.add(txtDocNo);
        txtDocNo.setBounds(130, 20, 110, 20);

        lblDocNo1.setDisplayedMnemonic('G');
        lblDocNo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocNo1.setText("Doc Date From :");
        jPanel1.add(lblDocNo1);
        lblDocNo1.setBounds(10, 50, 110, 15);

        jPanel1.add(txtDocFrom);
        txtDocFrom.setBounds(130, 50, 110, 20);

        lblDocNo2.setDisplayedMnemonic('G');
        lblDocNo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocNo2.setText("To :");
        jPanel1.add(lblDocNo2);
        lblDocNo2.setBounds(250, 50, 65, 15);

        jPanel1.add(txtDocTo);
        txtDocTo.setBounds(320, 50, 110, 20);

        lblAccountID2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccountID2.setText("Bank Ref. No. :");
        jPanel1.add(lblAccountID2);
        lblAccountID2.setBounds(10, 130, 110, 15);

        jPanel1.add(txtBankRefNo);
        txtBankRefNo.setBounds(130, 130, 110, 20);

        lblDocNo3.setDisplayedMnemonic('G');
        lblDocNo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocNo3.setText("Ref. Date From :");
        jPanel1.add(lblDocNo3);
        lblDocNo3.setBounds(10, 160, 110, 15);

        jPanel1.add(txtBankFrom);
        txtBankFrom.setBounds(130, 160, 110, 20);

        lblDocNo4.setDisplayedMnemonic('G');
        lblDocNo4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDocNo4.setText("To :");
        jPanel1.add(lblDocNo4);
        lblDocNo4.setBounds(260, 160, 65, 15);

        jPanel1.add(txtBankTo);
        txtBankTo.setBounds(330, 160, 110, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 39, 470, 260);

    }//GEN-END:initComponents

    private void txtMainCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMainCodeFocusLost
        // TODO add your handling code here:
         if (! txtMainCode.getText().trim().equals("")) {
            txtName.setText(clsAccount.getAccountName(txtMainCode.getText(),""));
        }
    }//GEN-LAST:event_txtMainCodeFocusLost

    private void txtMainCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMainCodeKeyPressed
        // TODO add your handling code here:
               if(evt.getKeyCode()==112) {
            
            LOV aList=new LOV();
            
            aList.SQL="SELECT MAIN_ACCOUNT_CODE,ACCOUNT_NAME FROM D_FIN_GL WHERE APPROVED=1 ORDER BY ACCOUNT_NAME";
            aList.ReturnCol=1;
            aList.ShowReturnCol=true;
            aList.DefaultSearchOn=2;
            aList.UseSpecifiedConn=true;
            aList.dbURL=FinanceGlobal.FinURL;
            
            if(aList.ShowLOV()) {
                txtMainCode.setText(aList.ReturnVal);
                txtName.setText(clsAccount.getAccountName(txtMainCode.getText(),""));
            }
        }
        
        
    }//GEN-LAST:event_txtMainCodeKeyPressed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        // TODO add your handling code here:
        strQuery=" WHERE COMPANY_ID="+EITLERPGLOBAL.gCompanyID+" ";
        Cancelled=false;
        getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdClearActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        // TODO add your handling code here:
        strQuery="";
        Cancelled=true;
        getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindActionPerformed
        // TODO add your handling code here:
       Cancelled=false;
       String subQuery="";
       
       strQuery=" WHERE A.COMPANY_ID="+Long.toString(EITLERPGLOBAL.gCompanyID)+" AND A.DOC_NO=B.DOC_NO ";
       
       if(!txtMainCode.getText().equals("")) {
         strQuery=strQuery+" AND A.MAIN_ACCOUNT_CODE='"+txtMainCode.getText().trim()+"' ";
       }
       
       if(!txtPartyCode.getText().equals("")) {
         strQuery=strQuery+" AND A.PARTY_CODE='"+txtPartyCode.getText().trim()+"' ";
       }

       if(!txtInvoiceNo.getText().equals("")) {
         strQuery=strQuery+" AND B.INVOICE_NO='"+txtInvoiceNo.getText().trim()+"' ";
       }
       
       if(!txtPartyCode.getText().equals("")) {
         strQuery=strQuery+" AND A.PARTY_CODE='"+txtPartyCode.getText().trim()+"' ";
       }
       if(!txtDocNo.getText().equals("")) {
         strQuery=strQuery+" AND A.DOC_NO='"+txtDocNo.getText().trim()+"' ";
       }
        if(!txtDocFrom.getText().equals("")) {
         strQuery=strQuery+" AND A.DOC_DATE>='"+EITLERPGLOBAL.formatDateDB(txtDocFrom.getText().trim())+"' ";
       }
       if(!txtDocTo.getText().equals("")) {
         strQuery=strQuery+" AND A.DOC_DATE<='"+EITLERPGLOBAL.formatDateDB(txtDocTo.getText().trim())+"' ";
       }
       if(!txtBankRefNo.getText().equals("")) {
         strQuery=strQuery+" AND A.BANK_REFERENCE_NO='"+txtBankRefNo.getText().trim()+"' ";
       }
       if(!txtBankFrom.getText().equals("")) {
         strQuery=strQuery+" AND A.BANK_REFERENCE_DATE>='"+EITLERPGLOBAL.formatDateDB(txtBankFrom.getText().trim())+"' ";
       }
       if(!txtBankTo.getText().equals("")) {
         strQuery=strQuery+" AND A.BANK_REFERENCE_DATE<='"+EITLERPGLOBAL.formatDateDB(txtBankTo.getText().trim())+"' ";
       }
       if(!txtInvoiceDate.getText().equals("")) {
         strQuery=strQuery+" AND B.INVOICE_DATE='"+EITLERPGLOBAL.formatDateDB(txtInvoiceDate.getText().trim())+"' ";
       }
       
       strQuery=strQuery;
       //========== End Sub Query ============//
       
       getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdFindActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccountID2;
    private javax.swing.JLabel lblDocNo;
    private javax.swing.JLabel lblDocNo1;
    private javax.swing.JLabel lblDocNo2;
    private javax.swing.JLabel lblDocNo3;
    private javax.swing.JLabel lblDocNo4;
    private javax.swing.JLabel lblInvoiceDate;
    private javax.swing.JLabel lblInvoiceNo;
    private javax.swing.JLabel lblMainCode;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPartyCode;
    private javax.swing.JTextField txtBankFrom;
    private javax.swing.JTextField txtBankRefNo;
    private javax.swing.JTextField txtBankTo;
    private javax.swing.JTextField txtDocFrom;
    private javax.swing.JTextField txtDocNo;
    private javax.swing.JTextField txtDocTo;
    private javax.swing.JTextField txtInvoiceDate;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtMainCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPartyCode;
    // End of variables declaration//GEN-END:variables
    


}
