/*
 * frmOBCReturnFind.java
 *
 * Created on August 9, 2011, 1:35 PM
 */

package EITLERP.Finance;

/**
 *
 * @author  Bhavesh
 */  
 
/*<APPLET CODE=frmOBCReturnFind.class HEIGHT=405 WIDTH=565></APPLET>*/

import javax.swing.*;
import java.awt.*;
import java.util.*;
import EITLERP.*;
 

public class frmOBCReturnFind extends javax.swing.JApplet {
    
    private EITLComboModel cmbStatusModel;

    public boolean Cancelled=false;
    public String strQuery;
        
    /** Initializes the applet frmGRNFind */
    public void init() {
        System.gc();
        setSize(565,180);
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        cmdFind = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDocNo = new javax.swing.JLabel();
        txtDocNo = new javax.swing.JTextField();
        lblDocNo1 = new javax.swing.JLabel();
        txtDocFrom = new javax.swing.JTextField();
        lblDocNo2 = new javax.swing.JLabel();
        txtDocTo = new javax.swing.JTextField();
        lblDocNo3 = new javax.swing.JLabel();
        txtOBCDocNo = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Find Records");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 12, 170, 15);

        cmdFind.setText("Find");
        cmdFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdFind.setNextFocusableComponent(cmdCancel);
        cmdFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindActionPerformed(evt);
            }
        });

        getContentPane().add(cmdFind);
        cmdFind.setBounds(482, 40, 70, 25);

        cmdCancel.setText("Cancel");
        cmdCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCancel.setNextFocusableComponent(cmdClear);
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        getContentPane().add(cmdCancel);
        cmdCancel.setBounds(482, 70, 70, 25);

        cmdClear.setText("Clear");
        cmdClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        getContentPane().add(cmdClear);
        cmdClear.setBounds(482, 110, 70, 25);

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblDocNo.setDisplayedMnemonic('G');
        lblDocNo.setText("Doc No");
        jPanel1.add(lblDocNo);
        lblDocNo.setBounds(10, 10, 105, 20);

        jPanel1.add(txtDocNo);
        txtDocNo.setBounds(120, 10, 132, 20);

        lblDocNo1.setDisplayedMnemonic('G');
        lblDocNo1.setText("Doc  Date From ");
        jPanel1.add(lblDocNo1);
        lblDocNo1.setBounds(10, 40, 105, 20);

        jPanel1.add(txtDocFrom);
        txtDocFrom.setBounds(120, 40, 132, 20);

        lblDocNo2.setDisplayedMnemonic('G');
        lblDocNo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDocNo2.setText("To");
        jPanel1.add(lblDocNo2);
        lblDocNo2.setBounds(260, 40, 30, 20);

        jPanel1.add(txtDocTo);
        txtDocTo.setBounds(300, 40, 132, 20);

        lblDocNo3.setDisplayedMnemonic('G');
        lblDocNo3.setText("OBC Doc No");
        jPanel1.add(lblDocNo3);
        lblDocNo3.setBounds(10, 70, 105, 20);

        txtOBCDocNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOBCDocNoKeyPressed(evt);
            }
        });

        jPanel1.add(txtOBCDocNo);
        txtOBCDocNo.setBounds(120, 70, 132, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 39, 470, 110);

    }//GEN-END:initComponents

    private void txtOBCDocNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOBCDocNoKeyPressed
        // TODO add your handling code here:
        try {
            
            if(evt.getKeyCode()==112) {
                
                LOV aList=new LOV();
                
                aList.SQL="SELECT  A.DOC_NO, DATE_FORMAT(A.DOC_DATE,'%d/%m/%Y') AS DOC_DATE,A.BANK_REFERENCE_NO, " +
                "DATE_FORMAT(A.BANK_REFERENCE_DATE,'%d/%m/%Y') AS BANK_REFERENCE_DATE " +
                "FROM D_FIN_OBC_INVOICE_HEADER A,D_FIN_OBC_INVOICE_DETAIL B " +
                "WHERE  A.DOC_NO = B.DOC_NO AND A.APPROVED = 1 AND A.CANCELLED = 0 " +
                "AND A.BANK_REFERENCE_DATE <= CURDATE() " +
                "AND A.MAIN_ACCOUNT_CODE IN('210010','210027')  " + //AND A.BANK_REFERENCE_NO NOT LIKE 'F6%'
                "AND (A.BANK_REFERENCE_NO LIKE 'BC%' OR A.BANK_REFERENCE_NO LIKE 'CC%') " +
                "AND A.BANK_REFERENCE_NO NOT IN(SELECT BANK_REFERENCE_NO FROM D_FIN_OBC ) " +
                "ORDER BY A.PARTY_CODE,A.BANK_REFERENCE_NO";
                
                aList.ReturnCol=1;
                //aList.SecondCol=2;
                aList.ShowReturnCol=true;
                aList.DefaultSearchOn=2;
                aList.UseSpecifiedConn=true;
                aList.dbURL=FinanceGlobal.FinURL;
                
                if(aList.ShowLOV()) {
                    txtOBCDocNo.setText(aList.ReturnVal);
                    
                }
                
            }
        }
        
        catch(Exception e)
        {}
        
        
    }//GEN-LAST:event_txtOBCDocNoKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        // TODO add your handling code here:
        strQuery=" WHERE COMPANY_ID="+EITLERPGLOBAL.gCompanyID+" ";
        Cancelled=false;
        getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdClearActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        // TODO add your handling code here:
        strQuery="";
        Cancelled=true;
        getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindActionPerformed
        // TODO add your handling code here:
       Cancelled=false;
       String subQuery="";
       
       strQuery=" WHERE COMPANY_ID="+Long.toString(EITLERPGLOBAL.gCompanyID)+" ";
       
      
       if(!txtDocNo.getText().equals("")) {
         strQuery=strQuery+" AND DOC_NO='"+txtDocNo.getText().trim()+"' ";
       }
        if(!txtDocFrom.getText().equals("")) {
         strQuery=strQuery+" AND DOC_DATE>='"+EITLERPGLOBAL.formatDateDB(txtDocFrom.getText().trim())+"' ";
       }
       if(!txtDocTo.getText().equals("")) {
         strQuery=strQuery+" AND DOC_DATE<='"+EITLERPGLOBAL.formatDateDB(txtDocTo.getText().trim())+"' ";
       }
       
       if(!txtOBCDocNo.getText().equals("")) {
         strQuery=strQuery+" AND OBC_DOC_NO='"+txtOBCDocNo.getText().trim()+"' ";
       }
       
       strQuery=strQuery;
       //========== End Sub Query ============//
       
       getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdFindActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDocNo;
    private javax.swing.JLabel lblDocNo1;
    private javax.swing.JLabel lblDocNo2;
    private javax.swing.JLabel lblDocNo3;
    private javax.swing.JTextField txtDocFrom;
    private javax.swing.JTextField txtDocNo;
    private javax.swing.JTextField txtDocTo;
    private javax.swing.JTextField txtOBCDocNo;
    // End of variables declaration//GEN-END:variables
    


}
