/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EITLERP.FeltSales;

import EITLERP.EITLERPGLOBAL;
import EITLERP.FeltSales.Reports.clsExcelExporter;
import EITLERP.FeltSales.common.JavaMail;
import EITLERP.data;
import java.io.File;

/**
 *
 * @author Dharmendra
 */
public class CurrentScheduleSalesPlanNotification {

    /**
     * @param args the command line arguments
     */
    private static clsExcelExporter exprt = new clsExcelExporter();

    public static void main(String[] args) {
        // TODO code application logic here
//        if (EITLERPGLOBAL.getCurrentDay() == 30) {
        if (EITLERPGLOBAL.getCurrentDay() == 1) {
            
            
////            data.Execute("DELETE FROM PRODUCTION.FELT_SALES_PIECE_REGISTER_01052019");
////            
////            data.Execute("INSERT INTO PRODUCTION.FELT_SALES_PIECE_REGISTER_01052019 SELECT * FROM PRODUCTION.FELT_SALES_PIECE_REGISTER");
////            
            data.Execute("DELETE FROM PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING"); 
            
            data.Execute("INSERT INTO PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING (MTH_CLOSING_DATE,PIECE_STAGE,PIECE_NO,PARTY_CODE,OC_MONTHYEAR,OC_LAST_DDMMYY,CURRENT_SCH_MTH,CURRENT_LAST_DDMMYY,SP_MONTH,SP_LAST_DDMMYY,SP_REMARK,NEW_CURRENT_SCH_MONTH,NEW_CURRENT_SCH_DDMMYY,NEW_SP_MONTH,NEW_SP_LAST_DDMMYY,NEW_SP_REMARK) SELECT SUBSTRING(NOW(),1,10),PR_PIECE_STAGE,PR_PIECE_NO,PR_PARTY_CODE,PR_OC_MONTHYEAR,PR_OC_LAST_DDMMYY,PR_CURRENT_SCH_MONTH,PR_CURRENT_SCH_LAST_DDMMYY,PR_SP_MONTHYEAR,PR_SP_LAST_DDMMYY,PR_SP_REMARKS,PR_CURRENT_SCH_MONTH,PR_CURRENT_SCH_LAST_DDMMYY,PR_SP_MONTHYEAR,PR_SP_LAST_DDMMYY,PR_SP_REMARKS FROM PRODUCTION.FELT_SALES_PIECE_REGISTER WHERE PR_OC_LAST_DDMMYY <= CURDATE() AND PR_OC_LAST_DDMMYY !='0000-00-00' AND PR_PIECE_STAGE IN ('IN STOCK','BSR','NEEDLING','PLANNING','WEAVING','FINISHING','MENDING','SEAMING','SPILICING','GIDC','OSG STOCK','SPIRALLING','ASSEMBLY','HEAT_SETTING','MARKING','SPLICING')");
            
            data.Execute("UPDATE PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING  SET NEW_CURRENT_SCH_DDMMYY  = LAST_DAY(CURDATE()) WHERE CURRENT_LAST_DDMMYY<=CURDATE() ");
            
            data.Execute("UPDATE PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING  SET NEW_CURRENT_SCH_MONTH  = CONCAT(DATE_FORMAT(NEW_CURRENT_SCH_DDMMYY,'%b'),' - ',YEAR(NEW_CURRENT_SCH_DDMMYY))");
            
            data.Execute("UPDATE PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING SET SP_MONTH = COALESCE(SP_MONTH,''),SP_LAST_DDMMYY = COALESCE(SP_LAST_DDMMYY,'0000-00-00')");
            
            data.Execute("UPDATE PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING SET NEW_SP_MONTH = OC_MONTHYEAR,NEW_SP_LAST_DDMMYY = OC_LAST_DDMMYY ,NEW_SP_REMARK = CONCAT('SPILLOVER ',OC_MONTHYEAR ,' TILL ' , DATE_FORMAT(MTH_CLOSING_DATE,'%d/%m/%Y')) WHERE SP_LAST_DDMMYY ='0000-00-00'  AND SP_MONTH ='' ");
            
//            data.Execute("SELECT * FROM PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING");
            
            data.Execute("UPDATE PRODUCTION.TMP_OC_SPILLOVER_MTH_CLOSING, PRODUCTION.FELT_SALES_PIECE_REGISTER SET  PR_CURRENT_SCH_LAST_DDMMYY= NEW_CURRENT_SCH_DDMMYY, PR_CURRENT_SCH_MONTH = NEW_CURRENT_SCH_MONTH, PR_SP_MONTHYEAR = NEW_SP_MONTH,PR_SP_LAST_DDMMYY = NEW_SP_LAST_DDMMYY ,PR_SP_REMARKS = NEW_SP_REMARK WHERE PR_PIECE_NO = PIECE_NO");
            
            data.Execute("TRUNCATE TABLE PRODUCTION.FELT_SALES_FOLLOWUP_DETAIL");
            
            String mntFor = data.getStringValueFromDB("SELECT CONCAT(DATE_FORMAT(NOW(),'%b'),'-',YEAR(NOW())) FROM DUAL");
            
            String pMessage = "Respected Sir, <br><br> These files contains sales plan pieces of WIP, IN Stock, BSR, OSG Stock <br> Please find attached document herewith <br><br>";
            
            String recievers = "vdshanbhag@dineshmills.com,narendramotiani@dineshmills.com,yrpatel@dineshmills.com,amitkanti@dineshmills.com,feltpp@dineshmills.com";
//            String recievers = "rishineekhra@dineshmills.com";
            
            String pCC = "aditya@dineshmills.com,abtewary@dineshmills.com,soumen@dineshmills.com,sdmlerp@dineshmills.com";
//            String pCC = "sdmlerp@dineshmills.com";
        
            String sql = "SELECT @a:=@a+1 AS 'Srno.', PR_PIECE_STAGE AS 'Piece Stage', PR_WIP_STATUS AS 'WIP Status', GROUP_DESC AS 'Group Name', PR_PARTY_CODE AS 'Party Code', PARTY_NAME AS 'Party Name', PR_PIECE_NO  AS 'Piece No', PR_MACHINE_NO AS 'Machine No', POSITION_DESC AS 'Position Desc', PR_BILL_PRODUCT_CODE AS 'Bill Product Code', PRODUCT_DESC AS 'Product Desc', PR_GROUP AS 'Group', PR_BILL_STYLE AS 'Bill Style', PR_BILL_LENGTH AS 'Bill Length', PR_BILL_WIDTH AS 'Bill Width', PR_BILL_GSM AS 'Bill GSM', PR_BILL_SQMTR AS 'Bill Sq.Mtr', PR_BILL_WEIGHT AS 'Bill Weight', PR_REQUESTED_MONTH AS 'Req Month', PR_OC_MONTHYEAR AS 'OC MONTH', PR_CURRENT_SCH_MONTH AS 'CURR SCH MONTH', PR_WARP_DATE AS 'WARP DATE', PR_WVG_DATE AS 'WVG DATE', PR_MND_DATE AS 'MND DATE', PR_NDL_DATE AS 'NDL DATE', PR_SEAM_DATE AS 'SEAM DATE', PR_FNSG_DATE AS 'FNSG DATE', PR_BALE_NO AS 'Bale No', PR_PACKED_DATE AS 'Bale Date', PR_INVOICE_NO AS 'Invoice No', PR_INVOICE_DATE AS 'Invoice Date', INCHARGE_NAME AS 'Incharge', PR_DELINK AS 'Obsolete Status', PR_OBSOLETE_DATE AS 'Obsolete Date', PR_DELINK_REASON AS 'Obsolete Reason', PR_SP_REMARKS AS 'Current Schedule Remark' FROM (SELECT @a:= 0) AS a,(SELECT * FROM PRODUCTION.FELT_SALES_PIECE_REGISTER WHERE PR_CURRENT_SCH_MONTH = CONCAT(DATE_FORMAT(NOW(),'%b'),' - ',YEAR(NOW())) ) AS PR LEFT JOIN (SELECT PARTY_CODE,PARTY_NAME FROM DINESHMILLS.D_SAL_PARTY_MASTER WHERE MAIN_ACCOUNT_CODE='210010' AND APPROVED=1 AND CANCELLED=0) AS PM ON PR.PR_PARTY_CODE=PM.PARTY_CODE LEFT JOIN (SELECT H.GROUP_CODE,H.GROUP_DESC,D.PARTY_CODE AS GROUP_PARTY_CODE FROM  PRODUCTION.FELT_GROUP_MASTER_HEADER H,PRODUCTION.FELT_GROUP_MASTER_DETAIL D WHERE H.GROUP_CODE=D.GROUP_CODE AND H.APPROVED=1 AND H.CANCELED=0) AS GM ON PR.PR_PARTY_CODE=GM.GROUP_PARTY_CODE LEFT JOIN (SELECT DISTINCT PRODUCT_CODE,PRODUCT_DESC FROM PRODUCTION.FELT_QLT_RATE_MASTER WHERE APPROVED=1 AND CANCELED=0 ORDER BY DOC_NO DESC) AS QM ON PR.PR_PRODUCT_CODE=QM.PRODUCT_CODE LEFT JOIN (SELECT * FROM PRODUCTION.FELT_MACHINE_POSITION_MST) AS MP ON PR.PR_POSITION_NO=MP.POSITION_NO LEFT JOIN (SELECT * FROM PRODUCTION.FELT_INCHARGE) AS IM ON PR.PR_INCHARGE=IM.INCHARGE_CD ";
            
            String sql1 = "SELECT @a:=@a+1 AS 'Srno.', PR_PIECE_STAGE AS 'Piece Stage', PR_WIP_STATUS AS 'WIP Status', GROUP_DESC AS 'Group Name', PR_PARTY_CODE AS 'Party Code', PARTY_NAME AS 'Party Name', PR_PIECE_NO  AS 'Piece No', PR_MACHINE_NO AS 'Machine No', POSITION_DESC AS 'Position Desc', PR_BILL_PRODUCT_CODE AS 'Bill Product Code', PRODUCT_DESC AS 'Product Desc', PR_GROUP AS 'Group', PR_BILL_STYLE AS 'Bill Style', PR_BILL_LENGTH AS 'Bill Length', PR_BILL_WIDTH AS 'Bill Width', PR_BILL_GSM AS 'Bill GSM', PR_BILL_SQMTR AS 'Bill Sq.Mtr', PR_BILL_WEIGHT AS 'Bill Weight', PR_REQUESTED_MONTH AS 'Req Month', PR_OC_MONTHYEAR AS 'OC MONTH', PR_CURRENT_SCH_MONTH AS 'CURR SCH MONTH', PR_WARP_DATE AS 'WARP DATE', PR_WVG_DATE AS 'WVG DATE', PR_MND_DATE AS 'MND DATE', PR_NDL_DATE AS 'NDL DATE', PR_SEAM_DATE AS 'SEAM DATE', PR_FNSG_DATE AS 'FNSG DATE', PR_BALE_NO AS 'Bale No', PR_PACKED_DATE AS 'Bale Date', PR_INVOICE_NO AS 'Invoice No', PR_INVOICE_DATE AS 'Invoice Date', INCHARGE_NAME AS 'Incharge', PR_DELINK AS 'Obsolete Status', PR_OBSOLETE_DATE AS 'Obsolete Date', PR_DELINK_REASON AS 'Obsolete Reason', PR_SP_REMARKS AS 'Current Schedule Remark' FROM (SELECT @a:= 0) AS a,(SELECT * FROM PRODUCTION.FELT_SALES_PIECE_REGISTER WHERE PR_PIECE_STAGE IN ('NEEDLING','MENDING','SEAMING','FINISHING','WEAVING','PLANNING','GIDC','SPIRALLING','ASSEMBLY','HEAT_SETTING','MARKING','SPLICING') AND PR_CURRENT_SCH_MONTH = CONCAT(DATE_FORMAT(NOW(),'%b'),' - ',YEAR(NOW())) ) AS PR LEFT JOIN (SELECT PARTY_CODE,PARTY_NAME FROM DINESHMILLS.D_SAL_PARTY_MASTER WHERE MAIN_ACCOUNT_CODE='210010' AND APPROVED=1 AND CANCELLED=0) AS PM ON PR.PR_PARTY_CODE=PM.PARTY_CODE LEFT JOIN (SELECT H.GROUP_CODE,H.GROUP_DESC,D.PARTY_CODE AS GROUP_PARTY_CODE FROM  PRODUCTION.FELT_GROUP_MASTER_HEADER H,PRODUCTION.FELT_GROUP_MASTER_DETAIL D WHERE H.GROUP_CODE=D.GROUP_CODE AND H.APPROVED=1 AND H.CANCELED=0) AS GM ON PR.PR_PARTY_CODE=GM.GROUP_PARTY_CODE LEFT JOIN (SELECT DISTINCT PRODUCT_CODE,PRODUCT_DESC FROM PRODUCTION.FELT_QLT_RATE_MASTER WHERE APPROVED=1 AND CANCELED=0 ORDER BY DOC_NO DESC) AS QM ON PR.PR_PRODUCT_CODE=QM.PRODUCT_CODE LEFT JOIN (SELECT * FROM PRODUCTION.FELT_MACHINE_POSITION_MST) AS MP ON PR.PR_POSITION_NO=MP.POSITION_NO LEFT JOIN (SELECT * FROM PRODUCTION.FELT_INCHARGE) AS IM ON PR.PR_INCHARGE=IM.INCHARGE_CD ";
            
            String sql2 = "SELECT @a:=@a+1 AS 'Srno.', PR_PIECE_STAGE AS 'Piece Stage', PR_WIP_STATUS AS 'WIP Status', GROUP_DESC AS 'Group Name', PR_PARTY_CODE AS 'Party Code', PARTY_NAME AS 'Party Name', PR_PIECE_NO  AS 'Piece No', PR_MACHINE_NO AS 'Machine No', POSITION_DESC AS 'Position Desc', PR_BILL_PRODUCT_CODE AS 'Bill Product Code', PRODUCT_DESC AS 'Product Desc', PR_GROUP AS 'Group', PR_BILL_STYLE AS 'Bill Style', PR_BILL_LENGTH AS 'Bill Length', PR_BILL_WIDTH AS 'Bill Width', PR_BILL_GSM AS 'Bill GSM', PR_BILL_SQMTR AS 'Bill Sq.Mtr', PR_BILL_WEIGHT AS 'Bill Weight', PR_REQUESTED_MONTH AS 'Req Month', PR_OC_MONTHYEAR AS 'OC MONTH', PR_CURRENT_SCH_MONTH AS 'CURR SCH MONTH', PR_WARP_DATE AS 'WARP DATE', PR_WVG_DATE AS 'WVG DATE', PR_MND_DATE AS 'MND DATE', PR_NDL_DATE AS 'NDL DATE', PR_SEAM_DATE AS 'SEAM DATE', PR_FNSG_DATE AS 'FNSG DATE', PR_BALE_NO AS 'Bale No', PR_PACKED_DATE AS 'Bale Date', PR_INVOICE_NO AS 'Invoice No', PR_INVOICE_DATE AS 'Invoice Date', INCHARGE_NAME AS 'Incharge', PR_DELINK AS 'Obsolete Status', PR_OBSOLETE_DATE AS 'Obsolete Date', PR_DELINK_REASON AS 'Obsolete Reason', PR_SP_REMARKS AS 'Current Schedule Remark' FROM (SELECT @a:= 0) AS a,(SELECT * FROM PRODUCTION.FELT_SALES_PIECE_REGISTER WHERE PR_PIECE_STAGE IN ('IN STOCK','BSR') AND PR_CURRENT_SCH_MONTH = CONCAT(DATE_FORMAT(NOW(),'%b'),' - ',YEAR(NOW())) ) AS PR LEFT JOIN (SELECT PARTY_CODE,PARTY_NAME FROM DINESHMILLS.D_SAL_PARTY_MASTER WHERE MAIN_ACCOUNT_CODE='210010' AND APPROVED=1 AND CANCELLED=0) AS PM ON PR.PR_PARTY_CODE=PM.PARTY_CODE LEFT JOIN (SELECT H.GROUP_CODE,H.GROUP_DESC,D.PARTY_CODE AS GROUP_PARTY_CODE FROM  PRODUCTION.FELT_GROUP_MASTER_HEADER H,PRODUCTION.FELT_GROUP_MASTER_DETAIL D WHERE H.GROUP_CODE=D.GROUP_CODE AND H.APPROVED=1 AND H.CANCELED=0) AS GM ON PR.PR_PARTY_CODE=GM.GROUP_PARTY_CODE LEFT JOIN (SELECT DISTINCT PRODUCT_CODE,PRODUCT_DESC FROM PRODUCTION.FELT_QLT_RATE_MASTER WHERE APPROVED=1 AND CANCELED=0 ORDER BY DOC_NO DESC) AS QM ON PR.PR_PRODUCT_CODE=QM.PRODUCT_CODE LEFT JOIN (SELECT * FROM PRODUCTION.FELT_MACHINE_POSITION_MST) AS MP ON PR.PR_POSITION_NO=MP.POSITION_NO LEFT JOIN (SELECT * FROM PRODUCTION.FELT_INCHARGE) AS IM ON PR.PR_INCHARGE=IM.INCHARGE_CD ";
            
            String sql3 = "SELECT @a:=@a+1 AS 'Srno.', PR_PIECE_STAGE AS 'Piece Stage', PR_WIP_STATUS AS 'WIP Status', GROUP_DESC AS 'Group Name', PR_PARTY_CODE AS 'Party Code', PARTY_NAME AS 'Party Name', PR_PIECE_NO  AS 'Piece No', PR_MACHINE_NO AS 'Machine No', POSITION_DESC AS 'Position Desc', PR_BILL_PRODUCT_CODE AS 'Bill Product Code', PRODUCT_DESC AS 'Product Desc', PR_GROUP AS 'Group', PR_BILL_STYLE AS 'Bill Style', PR_BILL_LENGTH AS 'Bill Length', PR_BILL_WIDTH AS 'Bill Width', PR_BILL_GSM AS 'Bill GSM', PR_BILL_SQMTR AS 'Bill Sq.Mtr', PR_BILL_WEIGHT AS 'Bill Weight', PR_REQUESTED_MONTH AS 'Req Month', PR_OC_MONTHYEAR AS 'OC MONTH', PR_CURRENT_SCH_MONTH AS 'CURR SCH MONTH', PR_WARP_DATE AS 'WARP DATE', PR_WVG_DATE AS 'WVG DATE', PR_MND_DATE AS 'MND DATE', PR_NDL_DATE AS 'NDL DATE', PR_SEAM_DATE AS 'SEAM DATE', PR_FNSG_DATE AS 'FNSG DATE', PR_BALE_NO AS 'Bale No', PR_PACKED_DATE AS 'Bale Date', PR_INVOICE_NO AS 'Invoice No', PR_INVOICE_DATE AS 'Invoice Date', INCHARGE_NAME AS 'Incharge', PR_DELINK AS 'Obsolete Status', PR_OBSOLETE_DATE AS 'Obsolete Date', PR_DELINK_REASON AS 'Obsolete Reason', PR_SP_REMARKS AS 'Current Schedule Remark' FROM (SELECT @a:= 0) AS a,(SELECT * FROM PRODUCTION.FELT_SALES_PIECE_REGISTER WHERE PR_PIECE_STAGE IN ('OSG STOCK') AND PR_CURRENT_SCH_MONTH = CONCAT(DATE_FORMAT(NOW(),'%b'),' - ',YEAR(NOW())) ) AS PR LEFT JOIN (SELECT PARTY_CODE,PARTY_NAME FROM DINESHMILLS.D_SAL_PARTY_MASTER WHERE MAIN_ACCOUNT_CODE='210010' AND APPROVED=1 AND CANCELLED=0) AS PM ON PR.PR_PARTY_CODE=PM.PARTY_CODE LEFT JOIN (SELECT H.GROUP_CODE,H.GROUP_DESC,D.PARTY_CODE AS GROUP_PARTY_CODE FROM  PRODUCTION.FELT_GROUP_MASTER_HEADER H,PRODUCTION.FELT_GROUP_MASTER_DETAIL D WHERE H.GROUP_CODE=D.GROUP_CODE AND H.APPROVED=1 AND H.CANCELED=0) AS GM ON PR.PR_PARTY_CODE=GM.GROUP_PARTY_CODE LEFT JOIN (SELECT DISTINCT PRODUCT_CODE,PRODUCT_DESC FROM PRODUCTION.FELT_QLT_RATE_MASTER WHERE APPROVED=1 AND CANCELED=0 ORDER BY DOC_NO DESC) AS QM ON PR.PR_PRODUCT_CODE=QM.PRODUCT_CODE LEFT JOIN (SELECT * FROM PRODUCTION.FELT_MACHINE_POSITION_MST) AS MP ON PR.PR_POSITION_NO=MP.POSITION_NO LEFT JOIN (SELECT * FROM PRODUCTION.FELT_INCHARGE) AS IM ON PR.PR_INCHARGE=IM.INCHARGE_CD ";
            
            exprt.fillData(sql3+"#"+sql2+"#"+sql1+"#"+sql, new File("/Email_Attachment/CurrentScheduleSalesPlanPieces_"+mntFor+".xls"), "OSG Stock#IN Stock,BSR#WIP#All");            
            String responce = sendNotificationMailWithAttachement("Sales Plan for Month of "+mntFor+"", pMessage, recievers, pCC, "/Email_Attachment/CurrentScheduleSalesPlanPieces_"+mntFor+".xls", "CurrentScheduleSalesPlanPieces_"+mntFor+".xls");
            System.out.println("Mail Response:" + responce);
        }

    }

    public static String sendNotificationMailWithAttachement(String pSubject, String pMessage, String recievers, String pcc, String Path, String PFiles) {
        try {
            System.out.println("Recivers : " + recievers);
            System.out.println("pSubject : " + pSubject);
            System.out.println("pMessage : " + pMessage);
            System.out.println("pCC      : " + pcc);
            System.out.println("Files    : " + PFiles);

            JavaMail.SendMailwithAttachment(recievers, pMessage, pSubject, pcc, Path, PFiles);
        } catch (Exception e) {
            System.out.println("Error Msg " + e.getMessage());
            e.printStackTrace();
        }
        return "Mail Sending Done....!";
    }

}
