/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EITLERP.FeltSales;

import EITLERP.EITLERPGLOBAL;
import EITLERP.FeltSales.Reports.clsExcelExporter;
import EITLERP.FeltSales.common.FeltInvCalc;
import EITLERP.FeltSales.common.JavaMail;
import EITLERP.FeltSales.common.clsOrderValueCalc;
import EITLERP.Finance.UtilFunctions;
import EITLERP.data;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 *
 * @author Dharmendra
 */
public class WIP_Production_Notification {

    /**
     * @param args the command line arguments
     */
    private static clsExcelExporter exprt = new clsExcelExporter();

    public static void main(String[] args) {
        // TODO code application logic here

        String maccepted, mconfirm, mwarp, mwoven, msplice, mmended, mneedled, mseamed, mfinishied, mreprocess,mheatset;
        mwoven = "SELECT @a:=@a+1 AS SR_NO,WIP_PIECE_NO AS PIECE,WIP_EXT_PIECE_NO AS EXT_PIECE_NO,WIP_PARTY_CODE AS PARTY_CODE,"
                + "COALESCE(PARTY_NAME,'') AS PARTY_NAME,COALESCE(WIP_MACHINE_NO,'') AS MACHINE_NO,COALESCE(WIP_POSITION_NO,'') AS POSITION_NO,"
                + "COALESCE(POSITION_DESC,'') AS POSITION_DESC,CONCAT(\"'\",COALESCE(WIP_UPN,'')) AS UPN,"
                + "CASE WHEN COALESCE(WIP_WARP_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WARP_DATE,'%d/%m/%Y') END AS WARP_DATE,"
                + "CASE WHEN COALESCE(WIP_WVG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WVG_DATE,'%d/%m/%Y') END AS WEAVING_DATE,"
                + "COALESCE(WIP_WEAVING_WEIGHT,'') AS WEAVING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_MND_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_MND_DATE,'%d/%m/%Y') END AS MENDING_DATE,"
                + "COALESCE(WIP_MENDING_WEIGHT,'') AS MENDING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_NDL_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_NDL_DATE,'%d/%m/%Y') END AS NEEDLING_DATE,"
                + "COALESCE(WIP_NEEDLING_WEIGHT,'') AS NEEDLING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_SEAM_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_SEAM_DATE,'%d/%m/%Y') END AS SEAMING_DATE,"
                + "COALESCE(WIP_SEAM_WEIGHT,'') AS SEAMING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_FNSG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_FNSG_DATE,'%d/%m/%Y') END AS FINISHING_DATE,"
                + "CASE WHEN COALESCE(WIP_ORDER_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_ORDER_DATE,'%d/%m/%Y') END AS ORDER_DATE,"
                + "COALESCE(WIP_BILL_PRODUCT_CODE,'') AS PRODUCT_CODE,COALESCE(PRODUCT_DESC,'') AS PRODUCT_DESC,COALESCE(WIP_GROUP,'') AS P_GROUP,"
                + "COALESCE(WIP_BILL_STYLE,'') AS STYLE,COALESCE(WIP_BILL_LENGTH,'') AS LENGTH,COALESCE(WIP_BILL_WIDTH,'') AS WIDTH,"
                + "COALESCE(WIP_BILL_GSM,'') AS GSM,COALESCE(WIP_BILL_SQMTR,'') AS DQMTR,COALESCE(WIP_BILL_WEIGHT,'') AS WEIGHT, COALESCE(WIP_DESIGN_THEO_PICKS,0) AS PICKS,"
                + "COALESCE(WIP_REQUESTED_MONTH,'') AS REQ_MONTH,COALESCE(WIP_OC_MONTHYEAR,'') AS OC_MONTH,COALESCE(WIP_CURRENT_SCH_MONTH,'') AS CURR_SCH_MONTH,"
                + "COALESCE(WIP_OBSOLETE,'') AS OBSOLETE,COALESCE(WIP_OBSOLETE_REASON,'') AS OBSOLETE_REASON,"
                + "CASE WHEN COALESCE(WIP_OBSOLETE_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_OBSOLETE_DATE,'%d/%m/%Y') END AS OBSOLETE_DATE  "
                + "from (select @a:=0) as a,(SELECT * FROM PRODUCTION.FELT_WIP_PIECE_REGISTER ORDER BY WIP_PIECE_NO,WIP_EXT_PIECE_NO)R "
                + "LEFT JOIN DINESHMILLS.D_SAL_PARTY_MASTER M "
                + "ON R.WIP_PARTY_CODE=M.PARTY_CODE "
                + "LEFT JOIN PRODUCTION.FELT_MACHINE_POSITION_MST MP "
                + "ON RIGHT(100+WIP_POSITION_NO,2)=RIGHT(100+MP.POSITION_NO,2) "
                + "LEFT JOIN PRODUCTION.FELT_QLT_RATE_MASTER QM "
                + "ON WIP_PRODUCT_CODE=QM.PRODUCT_CODE "
                + "WHERE QM.EFFECTIVE_TO='0000-00-00' AND WIP_PIECE_STAGE='WEAVING' AND WIP_PRIORITY_HOLD_CAN_FLAG=0 ";
                //+ "AND COALESCE(WIP_REJECTED_FLAG,0)=0";
        mmended = "SELECT @a:=@a+1 AS SR_NO,WIP_PIECE_NO AS PIECE,WIP_EXT_PIECE_NO AS EXT_PIECE_NO,WIP_PARTY_CODE AS PARTY_CODE,"
                + "COALESCE(PARTY_NAME,'') AS PARTY_NAME,COALESCE(WIP_MACHINE_NO,'') AS MACHINE_NO,COALESCE(WIP_POSITION_NO,'') AS POSITION_NO,"
                + "COALESCE(POSITION_DESC,'') AS POSITION_DESC,CONCAT(\"'\",COALESCE(WIP_UPN,'')) AS UPN,"
                + "CASE WHEN COALESCE(WIP_WARP_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WARP_DATE,'%d/%m/%Y') END AS WARP_DATE,"
                + "CASE WHEN COALESCE(WIP_WVG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WVG_DATE,'%d/%m/%Y') END AS WEAVING_DATE,"
                + "COALESCE(WIP_WEAVING_WEIGHT,'') AS WEAVING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_MND_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_MND_DATE,'%d/%m/%Y') END AS MENDING_DATE,"
                + "COALESCE(WIP_MENDING_WEIGHT,'') AS MENDING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_NDL_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_NDL_DATE,'%d/%m/%Y') END AS NEEDLING_DATE,"
                + "COALESCE(WIP_NEEDLING_WEIGHT,'') AS NEEDLING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_SEAM_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_SEAM_DATE,'%d/%m/%Y') END AS SEAMING_DATE,"
                + "COALESCE(WIP_SEAM_WEIGHT,'') AS SEAMING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_FNSG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_FNSG_DATE,'%d/%m/%Y') END AS FINISHING_DATE,"
                + "CASE WHEN COALESCE(WIP_ORDER_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_ORDER_DATE,'%d/%m/%Y') END AS ORDER_DATE,"
                + "COALESCE(WIP_BILL_PRODUCT_CODE,'') AS PRODUCT_CODE,COALESCE(PRODUCT_DESC,'') AS PRODUCT_DESC,COALESCE(WIP_GROUP,'') AS P_GROUP,"
                + "COALESCE(WIP_BILL_STYLE,'') AS STYLE,COALESCE(WIP_BILL_LENGTH,'') AS LENGTH,COALESCE(WIP_BILL_WIDTH,'') AS WIDTH,"
                + "COALESCE(WIP_BILL_GSM,'') AS GSM,COALESCE(WIP_BILL_SQMTR,'') AS DQMTR,COALESCE(WIP_BILL_WEIGHT,'') AS WEIGHT, COALESCE(WIP_DESIGN_THEO_PICKS,0) AS PICKS,"
                + "COALESCE(WIP_REQUESTED_MONTH,'') AS REQ_MONTH,COALESCE(WIP_OC_MONTHYEAR,'') AS OC_MONTH,COALESCE(WIP_CURRENT_SCH_MONTH,'') AS CURR_SCH_MONTH, "
                + "COALESCE(WIP_OBSOLETE,'') AS OBSOLETE,COALESCE(WIP_OBSOLETE_REASON,'') AS OBSOLETE_REASON,"
                + "CASE WHEN COALESCE(WIP_OBSOLETE_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_OBSOLETE_DATE,'%d/%m/%Y') END AS OBSOLETE_DATE  "                
                + "from (select @a:=0) as a,(SELECT * FROM PRODUCTION.FELT_WIP_PIECE_REGISTER ORDER BY WIP_PIECE_NO,WIP_EXT_PIECE_NO)R "
                + "LEFT JOIN DINESHMILLS.D_SAL_PARTY_MASTER M "
                + "ON R.WIP_PARTY_CODE=M.PARTY_CODE "
                + "LEFT JOIN PRODUCTION.FELT_MACHINE_POSITION_MST MP "
                + "ON RIGHT(100+WIP_POSITION_NO,2)=RIGHT(100+MP.POSITION_NO,2) "
                + "LEFT JOIN PRODUCTION.FELT_QLT_RATE_MASTER QM "
                + "ON WIP_PRODUCT_CODE=QM.PRODUCT_CODE "
                + "WHERE QM.EFFECTIVE_TO='0000-00-00' AND WIP_PIECE_STAGE='MENDING' AND WIP_PRIORITY_HOLD_CAN_FLAG=0 ";
                //+ "AND COALESCE(WIP_REJECTED_FLAG,0)=0";
        
        mheatset = "SELECT @a:=@a+1 AS SR_NO,WIP_PIECE_NO AS PIECE,WIP_EXT_PIECE_NO AS EXT_PIECE_NO,WIP_PARTY_CODE AS PARTY_CODE,"
                + "COALESCE(PARTY_NAME,'') AS PARTY_NAME,COALESCE(WIP_MACHINE_NO,'') AS MACHINE_NO,COALESCE(WIP_POSITION_NO,'') AS POSITION_NO,"
                + "COALESCE(POSITION_DESC,'') AS POSITION_DESC,CONCAT(\"'\",COALESCE(WIP_UPN,'')) AS UPN,"
                + "CASE WHEN COALESCE(WIP_WARP_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WARP_DATE,'%d/%m/%Y') END AS WARP_DATE,"
                + "CASE WHEN COALESCE(WIP_WVG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WVG_DATE,'%d/%m/%Y') END AS WEAVING_DATE,"
                + "COALESCE(WIP_WEAVING_WEIGHT,'') AS WEAVING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_MND_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_MND_DATE,'%d/%m/%Y') END AS MENDING_DATE,"
                + "COALESCE(WIP_MENDING_WEIGHT,'') AS MENDING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_HEATSET_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_HEATSET_DATE,'%d/%m/%Y') END AS HEATSETTING_DATE,"
                + "CASE WHEN COALESCE(WIP_NDL_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_NDL_DATE,'%d/%m/%Y') END AS NEEDLING_DATE,"
                + "COALESCE(WIP_NEEDLING_WEIGHT,'') AS NEEDLING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_SEAM_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_SEAM_DATE,'%d/%m/%Y') END AS SEAMING_DATE,"
                + "COALESCE(WIP_SEAM_WEIGHT,'') AS SEAMING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_FNSG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_FNSG_DATE,'%d/%m/%Y') END AS FINISHING_DATE,"
                + "CASE WHEN COALESCE(WIP_ORDER_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_ORDER_DATE,'%d/%m/%Y') END AS ORDER_DATE,"
                + "COALESCE(WIP_BILL_PRODUCT_CODE,'') AS PRODUCT_CODE,COALESCE(PRODUCT_DESC,'') AS PRODUCT_DESC,COALESCE(WIP_GROUP,'') AS P_GROUP,"
                + "COALESCE(WIP_BILL_STYLE,'') AS STYLE,COALESCE(WIP_BILL_LENGTH,'') AS LENGTH,COALESCE(WIP_BILL_WIDTH,'') AS WIDTH,"
                + "COALESCE(WIP_BILL_GSM,'') AS GSM,COALESCE(WIP_BILL_SQMTR,'') AS DQMTR,COALESCE(WIP_BILL_WEIGHT,'') AS WEIGHT, COALESCE(WIP_DESIGN_THEO_PICKS,0) AS PICKS,"
                + "COALESCE(WIP_REQUESTED_MONTH,'') AS REQ_MONTH,COALESCE(WIP_OC_MONTHYEAR,'') AS OC_MONTH,COALESCE(WIP_CURRENT_SCH_MONTH,'') AS CURR_SCH_MONTH, "
                + "COALESCE(WIP_OBSOLETE,'') AS OBSOLETE,COALESCE(WIP_OBSOLETE_REASON,'') AS OBSOLETE_REASON,"
                + "CASE WHEN COALESCE(WIP_OBSOLETE_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_OBSOLETE_DATE,'%d/%m/%Y') END AS OBSOLETE_DATE  "                
                + "from (select @a:=0) as a,(SELECT * FROM PRODUCTION.FELT_WIP_PIECE_REGISTER ORDER BY WIP_PIECE_NO,WIP_EXT_PIECE_NO)R "
                + "LEFT JOIN DINESHMILLS.D_SAL_PARTY_MASTER M "
                + "ON R.WIP_PARTY_CODE=M.PARTY_CODE "
                + "LEFT JOIN PRODUCTION.FELT_MACHINE_POSITION_MST MP "
                + "ON RIGHT(100+WIP_POSITION_NO,2)=RIGHT(100+MP.POSITION_NO,2) "
                + "LEFT JOIN PRODUCTION.FELT_QLT_RATE_MASTER QM "
                + "ON WIP_PRODUCT_CODE=QM.PRODUCT_CODE "
                + "WHERE QM.EFFECTIVE_TO='0000-00-00' AND WIP_PIECE_STAGE='HEAT_SETTING' AND WIP_PRIORITY_HOLD_CAN_FLAG=0 ";
                //+ "AND COALESCE(WIP_REJECTED_FLAG,0)=0";
        
        
        mneedled = "SELECT @a:=@a+1 AS SR_NO,WIP_PIECE_NO AS PIECE,WIP_EXT_PIECE_NO AS EXT_PIECE_NO,WIP_PARTY_CODE AS PARTY_CODE,"
                + "COALESCE(PARTY_NAME,'') AS PARTY_NAME,COALESCE(WIP_MACHINE_NO,'') AS MACHINE_NO,COALESCE(WIP_POSITION_NO,'') AS POSITION_NO,"
                + "COALESCE(POSITION_DESC,'') AS POSITION_DESC,CONCAT(\"'\",COALESCE(WIP_UPN,'')) AS UPN,"
                + "CASE WHEN COALESCE(WIP_WARP_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WARP_DATE,'%d/%m/%Y') END AS WARP_DATE,"
                + "CASE WHEN COALESCE(WIP_WVG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WVG_DATE,'%d/%m/%Y') END AS WEAVING_DATE,"
                + "COALESCE(WIP_WEAVING_WEIGHT,'') AS WEAVING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_MND_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_MND_DATE,'%d/%m/%Y') END AS MENDING_DATE,"
                + "COALESCE(WIP_MENDING_WEIGHT,'') AS MENDING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_HEATSET_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_HEATSET_DATE,'%d/%m/%Y') END AS HEATSETTING_DATE,"
                + "CASE WHEN COALESCE(WIP_NDL_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_NDL_DATE,'%d/%m/%Y') END AS NEEDLING_DATE,"
                + "COALESCE(WIP_NEEDLING_WEIGHT,'') AS NEEDLING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_SEAM_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_SEAM_DATE,'%d/%m/%Y') END AS SEAMING_DATE,"
                + "COALESCE(WIP_SEAM_WEIGHT,'') AS SEAMING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_FNSG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_FNSG_DATE,'%d/%m/%Y') END AS FINISHING_DATE,"
                + "CASE WHEN COALESCE(WIP_ORDER_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_ORDER_DATE,'%d/%m/%Y') END AS ORDER_DATE,"
                + "COALESCE(WIP_BILL_PRODUCT_CODE,'') AS PRODUCT_CODE,COALESCE(PRODUCT_DESC,'') AS PRODUCT_DESC,COALESCE(WIP_GROUP,'') AS P_GROUP,"
                + "COALESCE(WIP_BILL_STYLE,'') AS STYLE,COALESCE(WIP_BILL_LENGTH,'') AS LENGTH,COALESCE(WIP_BILL_WIDTH,'') AS WIDTH,"
                + "COALESCE(WIP_BILL_GSM,'') AS GSM,COALESCE(WIP_BILL_SQMTR,'') AS DQMTR,COALESCE(WIP_BILL_WEIGHT,'') AS WEIGHT, COALESCE(WIP_DESIGN_THEO_PICKS,0) AS PICKS,"
                + "COALESCE(WIP_REQUESTED_MONTH,'') AS REQ_MONTH,COALESCE(WIP_OC_MONTHYEAR,'') AS OC_MONTH,COALESCE(WIP_CURRENT_SCH_MONTH,'') AS CURR_SCH_MONTH, "
                + "COALESCE(WIP_OBSOLETE,'') AS OBSOLETE,COALESCE(WIP_OBSOLETE_REASON,'') AS OBSOLETE_REASON,"
                + "CASE WHEN COALESCE(WIP_OBSOLETE_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_OBSOLETE_DATE,'%d/%m/%Y') END AS OBSOLETE_DATE  "                
                + "from (select @a:=0) as a,(SELECT * FROM PRODUCTION.FELT_WIP_PIECE_REGISTER ORDER BY WIP_PIECE_NO,WIP_EXT_PIECE_NO)R "
                + "LEFT JOIN DINESHMILLS.D_SAL_PARTY_MASTER M "
                + "ON R.WIP_PARTY_CODE=M.PARTY_CODE "
                + "LEFT JOIN PRODUCTION.FELT_MACHINE_POSITION_MST MP "
                + "ON RIGHT(100+WIP_POSITION_NO,2)=RIGHT(100+MP.POSITION_NO,2) " 
                + "LEFT JOIN PRODUCTION.FELT_QLT_RATE_MASTER QM "
                + "ON WIP_PRODUCT_CODE=QM.PRODUCT_CODE "
                + "WHERE QM.EFFECTIVE_TO='0000-00-00' AND WIP_PIECE_STAGE='NEEDLING' AND "
                //+ "COALESCE(WIP_REJECTED_FLAG,0)=0 AND "
                + "((WIP_PRIORITY_HOLD_CAN_FLAG=0 AND COALESCE(WIP_PIECE_AB_FLAG,'')='AB') OR (WIP_PRIORITY_HOLD_CAN_FLAG=0 AND COALESCE(WIP_PIECE_AB_FLAG,'')=''))";
        mseamed = "SELECT @a:=@a+1 AS SR_NO,WIP_PIECE_NO AS PIECE,WIP_EXT_PIECE_NO AS EXT_PIECE_NO,WIP_PARTY_CODE AS PARTY_CODE,"
                + "COALESCE(PARTY_NAME,'') AS PARTY_NAME,COALESCE(WIP_MACHINE_NO,'') AS MACHINE_NO,COALESCE(WIP_POSITION_NO,'') AS POSITION_NO,"
                + "COALESCE(POSITION_DESC,'') AS POSITION_DESC,CONCAT(\"'\",COALESCE(WIP_UPN,'')) AS UPN,"
                + "CASE WHEN COALESCE(WIP_WARP_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WARP_DATE,'%d/%m/%Y') END AS WARP_DATE,"
                + "CASE WHEN COALESCE(WIP_WVG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WVG_DATE,'%d/%m/%Y') END AS WEAVING_DATE,"
                + "COALESCE(WIP_WEAVING_WEIGHT,'') AS WEAVING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_MND_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_MND_DATE,'%d/%m/%Y') END AS MENDING_DATE,"
                + "COALESCE(WIP_MENDING_WEIGHT,'') AS MENDING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_HEATSET_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_HEATSET_DATE,'%d/%m/%Y') END AS HEATSETTING_DATE,"
                + "CASE WHEN COALESCE(WIP_NDL_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_NDL_DATE,'%d/%m/%Y') END AS NEEDLING_DATE,"
                + "COALESCE(WIP_NEEDLING_WEIGHT,'') AS NEEDLING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_SEAM_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_SEAM_DATE,'%d/%m/%Y') END AS SEAMING_DATE,"
                + "COALESCE(WIP_SEAM_WEIGHT,'') AS SEAMING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_FNSG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_FNSG_DATE,'%d/%m/%Y') END AS FINISHING_DATE,"
                + "CASE WHEN COALESCE(WIP_ORDER_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_ORDER_DATE,'%d/%m/%Y') END AS ORDER_DATE,"
                + "COALESCE(WIP_BILL_PRODUCT_CODE,'') AS PRODUCT_CODE,COALESCE(PRODUCT_DESC,'') AS PRODUCT_DESC,COALESCE(WIP_GROUP,'') AS P_GROUP,"
                + "COALESCE(WIP_BILL_STYLE,'') AS STYLE,COALESCE(WIP_BILL_LENGTH,'') AS LENGTH,COALESCE(WIP_BILL_WIDTH,'') AS WIDTH,"
                + "COALESCE(WIP_BILL_GSM,'') AS GSM,COALESCE(WIP_BILL_SQMTR,'') AS DQMTR,COALESCE(WIP_BILL_WEIGHT,'') AS WEIGHT, COALESCE(WIP_DESIGN_THEO_PICKS,0) AS PICKS,"
                + "COALESCE(WIP_REQUESTED_MONTH,'') AS REQ_MONTH,COALESCE(WIP_OC_MONTHYEAR,'') AS OC_MONTH,COALESCE(WIP_CURRENT_SCH_MONTH,'') AS CURR_SCH_MONTH, "
                + "COALESCE(WIP_OBSOLETE,'') AS OBSOLETE,COALESCE(WIP_OBSOLETE_REASON,'') AS OBSOLETE_REASON,"
                + "CASE WHEN COALESCE(WIP_OBSOLETE_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_OBSOLETE_DATE,'%d/%m/%Y') END AS OBSOLETE_DATE  "                
                + "from (select @a:=0) as a,(SELECT * FROM PRODUCTION.FELT_WIP_PIECE_REGISTER ORDER BY WIP_PIECE_NO,WIP_EXT_PIECE_NO)R "
                + "LEFT JOIN DINESHMILLS.D_SAL_PARTY_MASTER M "
                + "ON R.WIP_PARTY_CODE=M.PARTY_CODE "
                + "LEFT JOIN PRODUCTION.FELT_MACHINE_POSITION_MST MP "
                + "ON RIGHT(100+WIP_POSITION_NO,2)=RIGHT(100+MP.POSITION_NO,2) "
                + "LEFT JOIN PRODUCTION.FELT_QLT_RATE_MASTER QM "
                + "ON WIP_PRODUCT_CODE=QM.PRODUCT_CODE "
                + "WHERE QM.EFFECTIVE_TO='0000-00-00' AND WIP_PIECE_STAGE='SEAMING' "
                //+ "AND COALESCE(WIP_REJECTED_FLAG,0)=0 "
                + "AND WIP_PRIORITY_HOLD_CAN_FLAG=0 AND WIP_GROUP='HDS'";
        mfinishied = "SELECT @a:=@a+1 AS SR_NO,WIP_PIECE_NO AS PIECE,WIP_EXT_PIECE_NO AS EXT_PIECE_NO,WIP_PARTY_CODE AS PARTY_CODE,"
                + "COALESCE(PARTY_NAME,'') AS PARTY_NAME,COALESCE(WIP_MACHINE_NO,'') AS MACHINE_NO,COALESCE(WIP_POSITION_NO,'') AS POSITION_NO,"
                + "COALESCE(POSITION_DESC,'') AS POSITION_DESC,CONCAT(\"'\",COALESCE(WIP_UPN,'')) AS UPN,"
                + "CASE WHEN COALESCE(WIP_WARP_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WARP_DATE,'%d/%m/%Y') END AS WARP_DATE,"
                + "CASE WHEN COALESCE(WIP_WVG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_WVG_DATE,'%d/%m/%Y') END AS WEAVING_DATE,"
                + "COALESCE(WIP_WEAVING_WEIGHT,'') AS WEAVING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_MND_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_MND_DATE,'%d/%m/%Y') END AS MENDING_DATE,"
                + "COALESCE(WIP_MENDING_WEIGHT,'') AS MENDING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_HEATSET_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_HEATSET_DATE,'%d/%m/%Y') END AS HEATSETTING_DATE,"
                + "CASE WHEN COALESCE(WIP_NDL_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_NDL_DATE,'%d/%m/%Y') END AS NEEDLING_DATE,"
                + "COALESCE(WIP_NEEDLING_WEIGHT,'') AS NEEDLING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_SEAM_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_SEAM_DATE,'%d/%m/%Y') END AS SEAMING_DATE,"
                + "COALESCE(WIP_SEAM_WEIGHT,'') AS SEAMING_WEIGHT,"
                + "CASE WHEN COALESCE(WIP_FNSG_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_FNSG_DATE,'%d/%m/%Y') END AS FINISHING_DATE,"
                + "CASE WHEN COALESCE(WIP_ORDER_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_ORDER_DATE,'%d/%m/%Y') END AS ORDER_DATE,"
                + "COALESCE(WIP_BILL_PRODUCT_CODE,'') AS PRODUCT_CODE,COALESCE(PRODUCT_DESC,'') AS PRODUCT_DESC,COALESCE(WIP_GROUP,'') AS P_GROUP,"
                + "COALESCE(WIP_BILL_STYLE,'') AS STYLE,COALESCE(WIP_BILL_LENGTH,'') AS LENGTH,COALESCE(WIP_BILL_WIDTH,'') AS WIDTH,"
                + "COALESCE(WIP_BILL_GSM,'') AS GSM,COALESCE(WIP_BILL_SQMTR,'') AS DQMTR,COALESCE(WIP_BILL_WEIGHT,'') AS WEIGHT, COALESCE(WIP_DESIGN_THEO_PICKS,0) AS PICKS,"
                + "COALESCE(WIP_REQUESTED_MONTH,'') AS REQ_MONTH,COALESCE(WIP_OC_MONTHYEAR,'') AS OC_MONTH,COALESCE(WIP_CURRENT_SCH_MONTH,'') AS CURR_SCH_MONTH, "
                + "COALESCE(WIP_OBSOLETE,'') AS OBSOLETE,COALESCE(WIP_OBSOLETE_REASON,'') AS OBSOLETE_REASON,"
                + "CASE WHEN COALESCE(WIP_OBSOLETE_DATE,'0000-00-00')='0000-00-00' THEN '' ELSE DATE_FORMAT(WIP_OBSOLETE_DATE,'%d/%m/%Y') END AS OBSOLETE_DATE  "                
                + "from (select @a:=0) as a,(SELECT * FROM PRODUCTION.FELT_WIP_PIECE_REGISTER ORDER BY WIP_PIECE_NO,WIP_EXT_PIECE_NO)R "
                + "LEFT JOIN DINESHMILLS.D_SAL_PARTY_MASTER M "
                + "ON R.WIP_PARTY_CODE=M.PARTY_CODE "
                + "LEFT JOIN PRODUCTION.FELT_MACHINE_POSITION_MST MP "
                + "ON RIGHT(100+WIP_POSITION_NO,2)=RIGHT(100+MP.POSITION_NO,2) "
                + "LEFT JOIN PRODUCTION.FELT_QLT_RATE_MASTER QM "
                + "ON WIP_PRODUCT_CODE=QM.PRODUCT_CODE "
                + "WHERE QM.EFFECTIVE_TO='0000-00-00' AND WIP_PIECE_STAGE='FINISHING' "
                + "AND WIP_EXT_PIECE_NO NOT LIKE '%-A' AND  WIP_EXT_PIECE_NO NOT LIKE '%-B' ";
                //+ "AND COALESCE(WIP_REJECTED_FLAG,0)=0";

        String recievers = "yrpatel@dineshmills.com,amitkanti@dineshmills.com,feltpp@dineshmills.com,brdfltneedle@dineshmills.com,balgondapatil@dineshmills.com,brdfltfin@dineshmills.com,narendramotiani@dineshmills.com,hemantprajapati@dineshmills.com,raghavendra@dineshmills.com,brdfltweave1@dineshmills.com";

        exprt.fillData(mfinishied + "#" + mseamed + "#" + mneedled +"#" + mheatset + "#" + mmended + "#" + mwoven, new File("/Email_Attachment/Production.xls"), "FINISHING#SEAMING#NEEDLING#HEAT_SETTING#MENDING#WEAVING");
//        try {
//            FileOutputStream fos = new FileOutputStream("/Email_Attachment/Production.zip");
//            ZipOutputStream zipOS = new ZipOutputStream(fos);
//            writeToZipFile("Production.xls", zipOS);
//            
//            zipOS.close();
//            fos.close();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        String mdate = data.getStringValueFromDB("SELECT DATE_FORMAT(CURDATE(),'%d/%m/%Y') FROM DUAL");

        String responce = sendNotificationMailWithAttachement("WIP NOTIFICATION", "WIP NOTIFICATION AS ON "+mdate, recievers, "abtewary@dineshmills.com,rakeshdalal@dineshmills.com,sdmlerp@dineshmills.com", "/Email_Attachment/Production.xls", "Production.xls");
        System.out.println("Mail Response:" + responce);

    }

    public static String sendNotificationMailWithAttachement(String pSubject, String pMessage, String recievers, String pcc, String Path, String PFiles) {
        try {
            System.out.println("Recivers : " + recievers);
            System.out.println("pSubject : " + pSubject);
            System.out.println("pMessage : " + pMessage);
            System.out.println("pCC      : " + pcc);
            System.out.println("Files    : " + PFiles);

            JavaMail.SendMailwithAttachment(recievers, pMessage, pSubject, pcc, Path, PFiles);
        } catch (Exception e) {
            System.out.println("Error Msg " + e.getMessage());
            e.printStackTrace();
        }
        return "Mail Sending Done....!";
    }

    public static void writeToZipFile(String path, ZipOutputStream zipStream) throws FileNotFoundException, IOException {
        System.out.println("Writing file : '" + path + "' to zip file");
        File aFile = new File(path);
        FileInputStream fis = new FileInputStream(aFile);
        ZipEntry zipEntry = new ZipEntry(path);
        zipStream.putNextEntry(zipEntry);
        byte[] bytes = new byte[1024];
        int length;
        while ((length = fis.read(bytes)) >= 0) {
            zipStream.write(bytes, 0, length);
        }
        zipStream.closeEntry();
        fis.close();
    }

}
