/*
 * frmFindFeltOrderUpd.java
 * This form is used for searching  the details of Felt Order Piece No.
 * 
 * Created on November 30, 2014, 
 */

package EITLERP.Production.FeltWeavingLoom;
/**
 *
 * @author  Rahevar Dhavalsinh
 */

import EITLERP.EITLERPGLOBAL;


public class frmFindFeltWeavingLoom extends javax.swing.JApplet {
    
    public boolean Cancelled=true;
    public String stringFindQuery="";   
   
    public void init() {
        System.gc();
        setSize(355,169);
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        cmdFind = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        cmdClear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldtxtWeavingDate = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Find Felt Weaving Effecency data");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 7, 280, 15);

        cmdFind.setMnemonic('F');
        cmdFind.setText("Find");
        cmdFind.setToolTipText("Find Felt Order Updation/Amendment details by Amendment date");
        cmdFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdFind.setNextFocusableComponent(cmdCancel);
        cmdFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindActionPerformed(evt);
            }
        });

        getContentPane().add(cmdFind);
        cmdFind.setBounds(265, 30, 70, 25);

        cmdCancel.setText("Cancel");
        cmdCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCancel.setNextFocusableComponent(cmdClear);
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        getContentPane().add(cmdCancel);
        cmdCancel.setBounds(265, 67, 70, 25);

        cmdClear.setText("Clear");
        cmdClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdClear.setNextFocusableComponent(jTextFieldtxtWeavingDate);
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearActionPerformed(evt);
            }
        });

        getContentPane().add(cmdClear);
        cmdClear.setBounds(265, 104, 70, 25);

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabel2.setDisplayedMnemonic('G');
        jLabel2.setLabelFor(jTextFieldtxtWeavingDate);
        jLabel2.setText("Weaving Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 15);

        jPanel1.add(jTextFieldtxtWeavingDate);
        jTextFieldtxtWeavingDate.setBounds(110, 10, 130, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 247, 100);

    }//GEN-END:initComponents
    
    private void cmdClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearActionPerformed
        stringFindQuery="";        
    //    jTextFieldtxtWeavingDate.setText("");        
      //  jTextFieldtxtWvgProdNo.setText("");
      //  jTextFieldcmbShift.setText("");
    }//GEN-LAST:event_cmdClearActionPerformed
    
    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        stringFindQuery="";
        Cancelled=true;
        getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdCancelActionPerformed
    
    private void cmdFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindActionPerformed
        Cancelled=false;
        
        
        String txtWeavingDate = jTextFieldtxtWeavingDate.getText();       
        //String txtWvgProdNo = jTextFieldtxtWvgProdNo.getText();
        //String cmbShift = jTextShift.getText();        
        
        if(!txtWeavingDate.equals("")) {
            stringFindQuery=stringFindQuery+"WLO_WEAVING_DATE='"+EITLERPGLOBAL.formatDateDB(txtWeavingDate)+"'";
        }
        
        /*if(!txtWvgProdNo.equals("")) {
            stringFindQuery=stringFindQuery+" WLO_WVGPROD_NO ='"+ txtWvgProdNo +"'";
        }
        
        if(!cmbShift.equals("")) {
            stringFindQuery=stringFindQuery+" AND FLT_AMEND_ID ='"+ cmbShift +"'";
        }
         **/
        getParent().getParent().getParent().getParent().show(false);
         
    }//GEN-LAST:event_cmdFindActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdClear;
    private javax.swing.JButton cmdFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldtxtWeavingDate;
    // End of variables declaration//GEN-END:variables
    
}
