/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SDMLATTPAY;

import EITLERP.FeltSales.Reports.clsExcelExporter;
import EITLERP.FeltSales.common.JavaMail;
import EITLERP.data;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 *
 * @author Dharmendra
 */
public class Attendance_Shiftwise_Email {

    /**
     * @param args the command line arguments
     */
    private static clsExcelExporter exprt = new clsExcelExporter();

    public static void main(String[] args) {
        // TODO code application logic here
        String sql = "SELECT * FROM ( "
                + "SELECT DATE_FORMAT(PUNCHDATE,'%d/%m/%Y') AS 'PUNCH DATE',DPTNAME AS 'DEPARTMENT NAME',SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER IN (1,4) THEN 1 ELSE 0 END,0)) AS 'STAFF SHIFT 1',"
                + "SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER =2 THEN 1 ELSE 0 END,0)) AS 'STAFF SHIFT 2',SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER =3 THEN 1 ELSE 0 END,0)) AS 'STAFF SHIFT 3',"
                + "SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER IN ('WO','HL') THEN 1 ELSE 0 END,0)) AS 'STAFF WO',SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER IN (9) THEN 1 ELSE 0 END,0)) AS 'STAFF NO SHIFT',"
                + "SUM(COALESCE(CASE WHEN CTG ='STAFF' THEN 1 ELSE 0 END,0)) AS 'STAFF TOTAL',  SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER IN (1,4) THEN 1 ELSE 0 END,0)) AS 'WORKER SHIFT 1',SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER =2 THEN 1 ELSE 0 END,0)) AS 'WORKER SHIFT 2',"
                + "SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER =3 THEN 1 ELSE 0 END,0)) AS 'WORKER SHIFT 3',SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER IN ('WO','HL') THEN 1 ELSE 0 END,0)) AS 'WORKER WO',"
                + "SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER IN (9)  THEN 1 ELSE 0 END,0)) AS 'WORKER NO SHIFT',SUM(COALESCE(CASE WHEN CTG ='WORKER' THEN 1 ELSE 0 END,0)) AS 'WORKER TOTAL',SUM(COALESCE(CASE WHEN CTG IN ('WORKER','STAFF') THEN 1 ELSE 0 END,0)) AS TOTAL "
                + "FROM(  SELECT PUNCHDATE,DPTID,DPTNAME,SECID,SECNAME,EMPID,EMP_NAME,CASE WHEN SECID IN (2,5,9) THEN'STAFF' ELSE 'WORKER' END AS CTG,ALL_PUNCHES,SHIFT,SHIFT_CONSIDER,CONCAT(PRESENT_FIRST,PRESENT_SECOND) AS PRES,PRESENT_DAY,PUNCHES_NOS "
                + "FROM (SELECT * FROM (SELECT * FROM ( SELECT *, SEC_TO_TIME(TIME_TO_SEC(GP_FIRST_HALF) + TIME_TO_SEC(GP_SECOND_HALF) + TIME_TO_SEC(LATE_COMING_HRS) + TIME_TO_SEC(LUNCH_LATE_HRS) + TIME_TO_SEC(GP_ADDITIONAL_HRS) ) AS TOTAL_LATE_COMING "
                + "FROM SDMLATTPAY.ATT_DATA_DAILY_SUMMARY WHERE YEAR(PUNCHDATE)=YYYY AND MONTH(PUNCHDATE)=MM AND PUNCHDATE>= SUBDATE(CURDATE(), INTERVAL 1 DAY)  AND PUNCHDATE<= SUBDATE(CURDATE(), INTERVAL 1 DAY) AND SUBSTRING(EMPID,1,5) NOT IN ('BRD00') AND SUBSTRING(EMPID,1,3 )  IN ('BRD')  ) AS DAS "
                + "LEFT JOIN ( SELECT PAY_EMP_NO,EMP_NAME,EMP_DEPARTMENT,EMP_MAIN_CATEGORY,EMP_CATEGORY FROM SDMLATTPAY.ATTPAY_EMPMST ) AS EMP "
                + "ON DAS.EMPID=EMP.PAY_EMP_NO LEFT JOIN ( SELECT DPTID,NAME AS DPTNAME FROM SDMLATTPAY.ATT_DEPARTMENT_MASTER ) AS DPT "
                + "ON DPT.DPTID=EMP.EMP_DEPARTMENT LEFT JOIN ( SELECT SECID,NAME AS SECNAME FROM SDMLATTPAY.ATT_MAIN_CATEGORY_MASTER ) AS SEC "
                + "ON SEC.SECID=DAS.MAIN_CATEGORY LEFT JOIN ( SELECT CTGID,NAME AS CTGNAME FROM SDMLATTPAY.ATT_CATEGORY_MASTER ) AS CTG "
                + "ON CTG.CTGID=DAS.CATEGORY LEFT JOIN ( SELECT *,'YES' AS SSS FROM SDMLATTPAY.ATT_SPECIAL_SANCTION WHERE APPROVED=1 AND CANCELED=0 ) AS SS "
                + "ON DAS.EMPID=SS.EMP_CODE AND DAS.PUNCHDATE=SS.A_DATE ) AS DAS  LEFT JOIN ( SELECT SHIFT_ID,SHIFT_CONSIDER FROM SDMLATTPAY.ATT_SHIFT) AS SFT "
                + "ON DAS.SHIFT =SFT.SHIFT_ID) AS MM WHERE PRESENT_DAY >0 AND ALL_PUNCHES !='' "
                + "UNION ALL SELECT PUNCHDATE,DPTID,DPTNAME,SECID,SECNAME,EMPID,EMP_NAME,CASE WHEN SECID IN (2,5,9) THEN'STAFF' ELSE 'WORKER' END AS CTG,"
                + "ALL_PUNCHES,SHIFT,SHIFT_CONSIDER,CONCAT(PRESENT_FIRST,PRESENT_SECOND) AS PRES,PRESENT_DAY,PUNCHES_NOS FROM (SELECT * "
                + "FROM (SELECT * FROM ( SELECT *, SEC_TO_TIME(TIME_TO_SEC(GP_FIRST_HALF) + TIME_TO_SEC(GP_SECOND_HALF) + TIME_TO_SEC(LATE_COMING_HRS) + TIME_TO_SEC(LUNCH_LATE_HRS) + TIME_TO_SEC(GP_ADDITIONAL_HRS) ) AS TOTAL_LATE_COMING "
                + "FROM SDMLATTPAY.ATT_DATA_DAILY_SUMMARY WHERE YEAR(PUNCHDATE)=YYYY AND MONTH(PUNCHDATE)=MM AND PUNCHDATE>= SUBDATE(CURDATE(), INTERVAL 1 DAY) AND PUNCHDATE<= SUBDATE(CURDATE(), INTERVAL 1 DAY)  AND SUBSTRING(EMPID,1,5) NOT IN ('BRD00') AND SUBSTRING(EMPID,1,3 )  IN ('BRD')  ) AS DAS "
                + "LEFT JOIN ( SELECT PAY_EMP_NO,EMP_NAME,EMP_DEPARTMENT,EMP_MAIN_CATEGORY,EMP_CATEGORY FROM SDMLATTPAY.ATTPAY_EMPMST ) AS EMP ON DAS.EMPID=EMP.PAY_EMP_NO LEFT JOIN ( SELECT DPTID,NAME AS DPTNAME FROM SDMLATTPAY.ATT_DEPARTMENT_MASTER ) AS DPT ON DPT.DPTID=EMP.EMP_DEPARTMENT "
                + "LEFT JOIN ( SELECT SECID,NAME AS SECNAME FROM SDMLATTPAY.ATT_MAIN_CATEGORY_MASTER ) AS SEC ON SEC.SECID=DAS.MAIN_CATEGORY "
                + "LEFT JOIN ( SELECT CTGID,NAME AS CTGNAME FROM SDMLATTPAY.ATT_CATEGORY_MASTER ) AS CTG ON CTG.CTGID=DAS.CATEGORY "
                + "LEFT JOIN ( SELECT *,'YES' AS SSS FROM SDMLATTPAY.ATT_SPECIAL_SANCTION WHERE APPROVED=1 AND CANCELED=0 ) AS SS ON DAS.EMPID=SS.EMP_CODE AND DAS.PUNCHDATE=SS.A_DATE ) AS DAS  "
                + "LEFT JOIN ( SELECT SHIFT_ID,SHIFT_CONSIDER FROM SDMLATTPAY.ATT_SHIFT) AS SFT ON DAS.SHIFT =SFT.SHIFT_ID) AS MM WHERE PRESENT_DAY =0 AND ALL_PUNCHES !=''  AND PUNCHES_NOS > 1 ) AS MM GROUP BY  PUNCHDATE,DPTNAME "
                + ") AS PD "
                + "UNION ALL "
                + "SELECT '','','','','','','','','','','','','','','' FROM DUAL "
                + "UNION ALL "
                + "SELECT * FROM ( "
                + "SELECT DATE_FORMAT(PUNCHDATE,'%d/%m/%Y') AS 'PUNCH DATE','TOTAL' AS 'DEPARTMENT NAME',SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER IN (1,4) THEN 1 ELSE 0 END,0)) AS 'STAFF SHIFT 1',"
                + "SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER =2 THEN 1 ELSE 0 END,0)) AS 'STAFF SHIFT 2',SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER =3 THEN 1 ELSE 0 END,0)) AS 'STAFF SHIFT 3',"
                + "SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER IN ('WO','HL') THEN 1 ELSE 0 END,0)) AS 'STAFF WO',SUM(COALESCE(CASE WHEN CTG ='STAFF' AND SHIFT_CONSIDER IN (9) THEN 1 ELSE 0 END,0)) AS 'STAFF NO SHIFT',"
                + "SUM(COALESCE(CASE WHEN CTG ='STAFF' THEN 1 ELSE 0 END,0)) AS 'STAFF TOTAL',  SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER IN (1,4) THEN 1 ELSE 0 END,0)) AS 'WORKER SHIFT 1',SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER =2 THEN 1 ELSE 0 END,0)) AS 'WORKER SHIFT 2',"
                + "SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER =3 THEN 1 ELSE 0 END,0)) AS 'WORKER SHIFT 3',SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER IN ('WO','HL') THEN 1 ELSE 0 END,0)) AS 'WORKER WO',"
                + "SUM(COALESCE(CASE WHEN CTG ='WORKER' AND SHIFT_CONSIDER IN (9)  THEN 1 ELSE 0 END,0)) AS 'WORKER NO SHIFT',SUM(COALESCE(CASE WHEN CTG ='WORKER' THEN 1 ELSE 0 END,0)) AS 'WORKER TOTAL',SUM(COALESCE(CASE WHEN CTG IN ('WORKER','STAFF') THEN 1 ELSE 0 END,0)) AS TOTAL "
                + "FROM(  SELECT PUNCHDATE,DPTID,DPTNAME,SECID,SECNAME,EMPID,EMP_NAME,CASE WHEN SECID IN (2,5,9) THEN'STAFF' ELSE 'WORKER' END AS CTG,ALL_PUNCHES,SHIFT,SHIFT_CONSIDER,CONCAT(PRESENT_FIRST,PRESENT_SECOND) AS PRES,PRESENT_DAY,PUNCHES_NOS "
                + "FROM (SELECT * FROM (SELECT * FROM ( SELECT *, SEC_TO_TIME(TIME_TO_SEC(GP_FIRST_HALF) + TIME_TO_SEC(GP_SECOND_HALF) + TIME_TO_SEC(LATE_COMING_HRS) + TIME_TO_SEC(LUNCH_LATE_HRS) + TIME_TO_SEC(GP_ADDITIONAL_HRS) ) AS TOTAL_LATE_COMING "
                + "FROM SDMLATTPAY.ATT_DATA_DAILY_SUMMARY WHERE YEAR(PUNCHDATE)=YYYY AND MONTH(PUNCHDATE)=MM AND PUNCHDATE>= SUBDATE(CURDATE(), INTERVAL 1 DAY)  AND PUNCHDATE<= SUBDATE(CURDATE(), INTERVAL 1 DAY) AND SUBSTRING(EMPID,1,5) NOT IN ('BRD00') AND SUBSTRING(EMPID,1,3 )  IN ('BRD')  ) AS DAS "
                + "LEFT JOIN ( SELECT PAY_EMP_NO,EMP_NAME,EMP_DEPARTMENT,EMP_MAIN_CATEGORY,EMP_CATEGORY FROM SDMLATTPAY.ATTPAY_EMPMST ) AS EMP "
                + "ON DAS.EMPID=EMP.PAY_EMP_NO LEFT JOIN ( SELECT DPTID,NAME AS DPTNAME FROM SDMLATTPAY.ATT_DEPARTMENT_MASTER ) AS DPT "
                + "ON DPT.DPTID=EMP.EMP_DEPARTMENT LEFT JOIN ( SELECT SECID,NAME AS SECNAME FROM SDMLATTPAY.ATT_MAIN_CATEGORY_MASTER ) AS SEC "
                + "ON SEC.SECID=DAS.MAIN_CATEGORY LEFT JOIN ( SELECT CTGID,NAME AS CTGNAME FROM SDMLATTPAY.ATT_CATEGORY_MASTER ) AS CTG "
                + "ON CTG.CTGID=DAS.CATEGORY LEFT JOIN ( SELECT *,'YES' AS SSS FROM SDMLATTPAY.ATT_SPECIAL_SANCTION WHERE APPROVED=1 AND CANCELED=0 ) AS SS "
                + "ON DAS.EMPID=SS.EMP_CODE AND DAS.PUNCHDATE=SS.A_DATE ) AS DAS  LEFT JOIN ( SELECT SHIFT_ID,SHIFT_CONSIDER FROM SDMLATTPAY.ATT_SHIFT) AS SFT "
                + "ON DAS.SHIFT =SFT.SHIFT_ID) AS MM WHERE PRESENT_DAY >0 AND ALL_PUNCHES !='' "
                + "UNION ALL SELECT PUNCHDATE,DPTID,DPTNAME,SECID,SECNAME,EMPID,EMP_NAME,CASE WHEN SECID IN (2,5,9) THEN'STAFF' ELSE 'WORKER' END AS CTG,"
                + "ALL_PUNCHES,SHIFT,SHIFT_CONSIDER,CONCAT(PRESENT_FIRST,PRESENT_SECOND) AS PRES,PRESENT_DAY,PUNCHES_NOS "
                + "FROM (SELECT * FROM (SELECT * FROM ( SELECT *, SEC_TO_TIME(TIME_TO_SEC(GP_FIRST_HALF) + TIME_TO_SEC(GP_SECOND_HALF) + TIME_TO_SEC(LATE_COMING_HRS) + TIME_TO_SEC(LUNCH_LATE_HRS) + TIME_TO_SEC(GP_ADDITIONAL_HRS) ) AS TOTAL_LATE_COMING "
                + "FROM SDMLATTPAY.ATT_DATA_DAILY_SUMMARY WHERE YEAR(PUNCHDATE)=YYYY AND MONTH(PUNCHDATE)=MM AND PUNCHDATE>= SUBDATE(CURDATE(), INTERVAL 1 DAY) AND PUNCHDATE<= SUBDATE(CURDATE(), INTERVAL 1 DAY)  AND SUBSTRING(EMPID,1,5) NOT IN ('BRD00') AND SUBSTRING(EMPID,1,3 )  IN ('BRD')  ) AS DAS "
                + "LEFT JOIN ( SELECT PAY_EMP_NO,EMP_NAME,EMP_DEPARTMENT,EMP_MAIN_CATEGORY,EMP_CATEGORY FROM SDMLATTPAY.ATTPAY_EMPMST ) AS EMP ON DAS.EMPID=EMP.PAY_EMP_NO LEFT JOIN ( SELECT DPTID,NAME AS DPTNAME FROM SDMLATTPAY.ATT_DEPARTMENT_MASTER ) AS DPT ON DPT.DPTID=EMP.EMP_DEPARTMENT "
                + "LEFT JOIN ( SELECT SECID,NAME AS SECNAME FROM SDMLATTPAY.ATT_MAIN_CATEGORY_MASTER ) AS SEC ON SEC.SECID=DAS.MAIN_CATEGORY "
                + "LEFT JOIN ( SELECT CTGID,NAME AS CTGNAME FROM SDMLATTPAY.ATT_CATEGORY_MASTER ) AS CTG ON CTG.CTGID=DAS.CATEGORY "
                + "LEFT JOIN ( SELECT *,'YES' AS SSS FROM SDMLATTPAY.ATT_SPECIAL_SANCTION WHERE APPROVED=1 AND CANCELED=0 ) AS SS ON DAS.EMPID=SS.EMP_CODE AND DAS.PUNCHDATE=SS.A_DATE ) AS DAS  "
                + "LEFT JOIN ( SELECT SHIFT_ID,SHIFT_CONSIDER FROM SDMLATTPAY.ATT_SHIFT) AS SFT ON DAS.SHIFT =SFT.SHIFT_ID) AS MM WHERE PRESENT_DAY =0 AND ALL_PUNCHES !=''  AND PUNCHES_NOS > 1 ) AS MM GROUP BY  PUNCHDATE "
                + ") AS PU "
                + "ORDER BY 'PUNCH DATE','DEPARTMENT NAME' ";
//        System.out.println("SQL:" + sql);
        
        
        String sql1 = "SELECT DATE_FORMAT(PUNCHDATE,'%d/%m/%Y') AS 'PUNCH DATE',SHIFT_CONSIDER AS 'SHIFT CONSIDER',SHIFT AS 'SHIFT ID',"
                + "CTG AS 'CATEGORY',DPTNAME AS 'DEPARTMENT NAME',EMPID AS 'EMP ID',EMP_NAME AS 'EMP NAME',ALL_PUNCHES AS 'PUNCHES' "
                + "FROM (  SELECT PUNCHDATE,DPTID,DPTNAME,SECID,SECNAME,EMPID,EMP_NAME,CASE WHEN SECID IN (2,5,9) THEN 'STAFF' ELSE 'WORKER' END AS CTG,"
                + "ALL_PUNCHES,SHIFT,SHIFT_CONSIDER,CONCAT(PRESENT_FIRST,PRESENT_SECOND) AS PRES,PRESENT_DAY,PUNCHES_NOS "
                + "FROM (SELECT * FROM (SELECT * FROM ( SELECT *, SEC_TO_TIME(TIME_TO_SEC(GP_FIRST_HALF) + TIME_TO_SEC(GP_SECOND_HALF) + TIME_TO_SEC(LATE_COMING_HRS) + TIME_TO_SEC(LUNCH_LATE_HRS) + TIME_TO_SEC(GP_ADDITIONAL_HRS) ) AS TOTAL_LATE_COMING "
                + "FROM SDMLATTPAY.ATT_DATA_DAILY_SUMMARY WHERE YEAR(PUNCHDATE)=YYYY AND MONTH(PUNCHDATE)=MM AND PUNCHDATE>= SUBDATE(CURDATE(), INTERVAL 1 DAY)  "
                + "AND PUNCHDATE<= SUBDATE(CURDATE(), INTERVAL 1 DAY) AND SUBSTRING(EMPID,1,5) NOT IN ('BRD00') AND SUBSTRING(EMPID,1,3 )  IN ('BRD')  ) AS DAS "
                + "LEFT JOIN ( SELECT PAY_EMP_NO,EMP_NAME,EMP_DEPARTMENT,EMP_MAIN_CATEGORY,EMP_CATEGORY FROM SDMLATTPAY.ATTPAY_EMPMST ) AS EMP "
                + "ON DAS.EMPID=EMP.PAY_EMP_NO LEFT JOIN ( SELECT DPTID,NAME AS DPTNAME FROM SDMLATTPAY.ATT_DEPARTMENT_MASTER ) AS DPT "
                + "ON DPT.DPTID=EMP.EMP_DEPARTMENT LEFT JOIN ( SELECT SECID,NAME AS SECNAME FROM SDMLATTPAY.ATT_MAIN_CATEGORY_MASTER ) AS SEC "
                + "ON SEC.SECID=DAS.MAIN_CATEGORY LEFT JOIN ( SELECT CTGID,NAME AS CTGNAME FROM SDMLATTPAY.ATT_CATEGORY_MASTER ) AS CTG "
                + "ON CTG.CTGID=DAS.CATEGORY LEFT JOIN ( SELECT *,'YES' AS SSS FROM SDMLATTPAY.ATT_SPECIAL_SANCTION WHERE APPROVED=1 AND CANCELED=0 ) AS SS "
                + "ON DAS.EMPID=SS.EMP_CODE AND DAS.PUNCHDATE=SS.A_DATE ) AS DAS  LEFT JOIN ( SELECT SHIFT_ID,SHIFT_CONSIDER FROM SDMLATTPAY.ATT_SHIFT) AS SFT "
                + "ON DAS.SHIFT =SFT.SHIFT_ID) AS MM WHERE PRESENT_DAY >0 AND ALL_PUNCHES !='' "
                + "UNION ALL SELECT PUNCHDATE,DPTID,DPTNAME,SECID,SECNAME,EMPID,EMP_NAME,CASE WHEN SECID IN (2,5,9) THEN 'STAFF' ELSE 'WORKER' END AS CTG,"
                + "ALL_PUNCHES,SHIFT,SHIFT_CONSIDER,CONCAT(PRESENT_FIRST,PRESENT_SECOND) AS PRES,PRESENT_DAY,PUNCHES_NOS "
                + "FROM (SELECT * FROM (SELECT * FROM ( SELECT *, SEC_TO_TIME(TIME_TO_SEC(GP_FIRST_HALF) + TIME_TO_SEC(GP_SECOND_HALF) + TIME_TO_SEC(LATE_COMING_HRS) + TIME_TO_SEC(LUNCH_LATE_HRS) + TIME_TO_SEC(GP_ADDITIONAL_HRS) ) AS TOTAL_LATE_COMING "
                + "FROM SDMLATTPAY.ATT_DATA_DAILY_SUMMARY WHERE YEAR(PUNCHDATE)=YYYY AND MONTH(PUNCHDATE)=MM AND PUNCHDATE>= SUBDATE(CURDATE(), INTERVAL 1 DAY) AND PUNCHDATE<= SUBDATE(CURDATE(), INTERVAL 1 DAY)  "
                + "AND SUBSTRING(EMPID,1,5) NOT IN ('BRD00') AND SUBSTRING(EMPID,1,3 )  IN ('BRD')  ) AS DAS "
                + "LEFT JOIN ( SELECT PAY_EMP_NO,EMP_NAME,EMP_DEPARTMENT,EMP_MAIN_CATEGORY,EMP_CATEGORY FROM SDMLATTPAY.ATTPAY_EMPMST ) AS EMP "
                + "ON DAS.EMPID=EMP.PAY_EMP_NO LEFT JOIN ( SELECT DPTID,NAME AS DPTNAME FROM SDMLATTPAY.ATT_DEPARTMENT_MASTER ) AS DPT "
                + "ON DPT.DPTID=EMP.EMP_DEPARTMENT LEFT JOIN ( SELECT SECID,NAME AS SECNAME FROM SDMLATTPAY.ATT_MAIN_CATEGORY_MASTER ) AS SEC "
                + "ON SEC.SECID=DAS.MAIN_CATEGORY LEFT JOIN ( SELECT CTGID,NAME AS CTGNAME FROM SDMLATTPAY.ATT_CATEGORY_MASTER ) AS CTG "
                + "ON CTG.CTGID=DAS.CATEGORY LEFT JOIN ( SELECT *,'YES' AS SSS FROM SDMLATTPAY.ATT_SPECIAL_SANCTION WHERE APPROVED=1 AND CANCELED=0 ) AS SS "
                + "ON DAS.EMPID=SS.EMP_CODE AND DAS.PUNCHDATE=SS.A_DATE ) AS DAS  LEFT JOIN ( SELECT SHIFT_ID,SHIFT_CONSIDER FROM SDMLATTPAY.ATT_SHIFT) AS SFT "
                + "ON DAS.SHIFT =SFT.SHIFT_ID) AS MM WHERE PRESENT_DAY =0 AND ALL_PUNCHES !=''  AND PUNCHES_NOS > 1 ) AS MM ORDER BY PUNCHDATE,CTG,SHIFT_CONSIDER+0,DPTNAME,EMPID  ";
//        System.out.println("SQL:" + sql1);
//        String recievers = "rishineekhra@dineshmills.com,gaurang@dineshmills.com";
        //String recievers = "gaurang@dineshmills.com";
        String recievers = "sunil@dineshmills.com,manhardave@dineshmills.com,neelanjan@dineshmills.com,rishineekhra@dineshmills.com";
        // String recievers = "aditya@dineshmills.com";

        exprt.fillData(sql1 + "#" + sql, new File("/Email_Attachment/SHIFTWISE_ATTENDANCE.xls"), "DETAIL#SUMMARY");
        String mdate = data.getStringValueFromDB("SELECT DATE_FORMAT(SUBDATE(CURDATE(),INTERVAL 1 DAY),'%d/%m/%Y') FROM DUAL");
        String responce = sendNotificationMailWithAttachement("Shiftwise Attendance For " + mdate, "", recievers, "sdmlerp@dineshmills.com", "/Email_Attachment/SHIFTWISE_ATTENDANCE.xls", "SHIFTWISE_ATTENDANCE.xls");
        System.out.println("Mail Response:" + responce);

//        exprt.fillData(sql1, new File("/Email_Attachment/DATEWISE_DEPTWISE_ATT_DETAIL.xls"), "ATTDTL");
//        responce = sendNotificationMailWithAttachement("Attendance Detail For " + mdate, "", recievers, "sdmlerp@dineshmills.com", "/Email_Attachment/DATEWISE_DEPTWISE_ATT_DETAIL.xls", "DATEWISE_DEPTWISE_ATT_DETAIL.xls");
//        System.out.println("Mail Response:" + responce);
    }

    public static String sendNotificationMailWithAttachement(String pSubject, String pMessage, String recievers, String pcc, String Path, String PFiles) {
        try {
            System.out.println("Recivers : " + recievers);
            System.out.println("pSubject : " + pSubject);
            System.out.println("pMessage : " + pMessage);
            System.out.println("pCC      : " + pcc);
            System.out.println("Files    : " + PFiles);

            JavaMail.SendMailwithAttachment(recievers, pMessage, pSubject, pcc, Path, PFiles);
        } catch (Exception e) {
            System.out.println("Error Msg " + e.getMessage());
            e.printStackTrace();
        }
        return "Mail Sending Done....!";
    }

    public static void writeToZipFile(String path, ZipOutputStream zipStream) throws FileNotFoundException, IOException {
        System.out.println("Writing file : '" + path + "' to zip file");
        File aFile = new File(path);
        FileInputStream fis = new FileInputStream(aFile);
        ZipEntry zipEntry = new ZipEntry(path);
        zipStream.putNextEntry(zipEntry);
        byte[] bytes = new byte[1024];
        int length;
        while ((length = fis.read(bytes)) >= 0) {
            zipStream.write(bytes, 0, length);
        }
        zipStream.closeEntry();
        fis.close();
    }

}
