/*
 * frmMissing.java
 *
 * Created on August 5, 2005, 10:56 AM
 */

package EITLERP.Migration;

/**
 *
 * @author  root
 */

import java.sql.*;
import EITLERP.*;
import java.io.*;
import javax.swing.*;
import java.awt.*;


public class frmMissing extends javax.swing.JApplet {
    
    /** Initializes the applet frmMissing */
    public void init() {
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        
        getContentPane().setLayout(null);
        
        jLabel1.setText("Missing Unapproved Document Report (All Modules)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 16, 389, 15);
        
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        getContentPane().add(jButton1);
        jButton1.setBounds(15, 106, 88, 25);
        
        lblStatus.setText("-");
        getContentPane().add(lblStatus);
        lblStatus.setBounds(13, 66, 282, 15);
        
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StartProcess();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
    
    
    private void StartProcess() {

        
        new Thread()
        {
           public void run()
           
           {
        try
        {
        ResultSet rsTmp,rsDoc;            
        BufferedWriter aFile=new BufferedWriter(new FileWriter(new File("MissingDocuments.txt")));
        
        //Module 1
        lblStatus.setText("ITEM ID");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT ITEM_ID FROM D_INV_ITEM_MASTER WHERE APPROVED=0 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : ITEM MASTER");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=1 AND DOC_NO='"+rsTmp.getString("ITEM_ID")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("ITEM_ID"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        
        //Module 2
        lblStatus.setText("PURCHASE REQUISITION");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT REQ_NO FROM D_INV_REQ_HEADER WHERE APPROVED=0 AND CANCELED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : Purchase Requisition");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=2 AND DOC_NO='"+rsTmp.getString("REQ_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("REQ_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        //Module 3
        lblStatus.setText("INDENT");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT INDENT_NO FROM D_INV_INDENT_HEADER WHERE APPROVED=0 AND CANCELED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : INDENT");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=3 AND DOC_NO='"+rsTmp.getString("INDENT_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("INDENT_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        //Module 5
        lblStatus.setText("MIR");
        lblStatus.repaint();
        
        
        rsTmp=data.getResult("SELECT MIR_NO FROM D_INV_MIR_HEADER WHERE APPROVED=0 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : MIR ");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=5 AND DOC_NO='"+rsTmp.getString("MIR_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("MIR_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
                
        
        //Module 7
        lblStatus.setText("GRN");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT GRN_NO FROM D_INV_GRN_HEADER WHERE APPROVED=0 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : GRN");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=7 AND DOC_NO='"+rsTmp.getString("GRN_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("GRN_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        
        //Module 14
        lblStatus.setText("ISSUE");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT ISSUE_NO FROM D_INV_ISSUE_HEADER WHERE APPROVED=0 AND CANCELED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : ISSUE ");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=14 AND DOC_NO='"+rsTmp.getString("ISSUE_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("ISSUE_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        //Module 21
        lblStatus.setText("PO GEN.");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT PO_NO FROM D_PUR_PO_HEADER WHERE APPROVED=0 AND PO_TYPE=1 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO GEN.");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=21 AND DOC_NO='"+rsTmp.getString("PO_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("PO_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        //Module 23
        lblStatus.setText("PO A CLASS");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT PO_NO FROM D_PUR_PO_HEADER WHERE APPROVED=0 AND PO_TYPE=3 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO A CLASS");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=23 AND DOC_NO='"+rsTmp.getString("PO_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("PO_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        //Module 24
        lblStatus.setText("PO RAW MATERIAL");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT PO_NO FROM D_PUR_PO_HEADER WHERE APPROVED=0 AND PO_TYPE=4 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO RAW MATERIAL");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=24 AND DOC_NO='"+rsTmp.getString("PO_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("PO_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        
        //Module 25
        lblStatus.setText("PO SPARES");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT PO_NO FROM D_PUR_PO_HEADER WHERE APPROVED=0 AND PO_TYPE=5 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO SPARES");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=25 AND DOC_NO='"+rsTmp.getString("PO_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("PO_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        
        //Module 26
        lblStatus.setText("PO CAPITAL");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT PO_NO FROM D_PUR_PO_HEADER WHERE APPROVED=0 AND PO_TYPE=6 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO CAPITAL");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=26 AND DOC_NO='"+rsTmp.getString("PO_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("PO_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        
        //Module 27
        lblStatus.setText("PO CONTRACT");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT PO_NO FROM D_PUR_PO_HEADER WHERE APPROVED=0 AND PO_TYPE=7 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO CONTRACT");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=27 AND DOC_NO='"+rsTmp.getString("PO_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("PO_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }


                
        
        //Module 28
        lblStatus.setText("PO AMEND GEN.");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT AMEND_NO FROM D_PUR_AMEND_HEADER WHERE APPROVED=0 AND PO_TYPE=1 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO AMEND GEN.");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=28 AND DOC_NO='"+rsTmp.getString("AMEND_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("AMEND_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        //Module 30
        lblStatus.setText("PO AMEND A CLASS");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT AMEND_NO FROM D_PUR_AMEND_HEADER WHERE APPROVED=0 AND PO_TYPE=3 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO AMEND A CLASS");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=30 AND DOC_NO='"+rsTmp.getString("AMEND_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("AMEND_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        //Module 37
        lblStatus.setText("SUPPLIER MASTER");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT SUPP_ID FROM D_COM_SUPP_MASTER WHERE APPROVED=0 AND BLOCKED='N'");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : SUPPLIER MASTER");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=37 AND DOC_NO='"+rsTmp.getInt("SUPP_ID")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(Integer.toString(rsTmp.getInt("SUPP_ID")));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        

        //Module 38
        lblStatus.setText("RIA");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT APPROVAL_NO FROM D_PUR_RATE_APPROVAL_HEADER WHERE APPROVED=0 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : RIA");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=38 AND DOC_NO='"+rsTmp.getString("APPROVAL_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("APPROVAL_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        //Module 44
        lblStatus.setText("DOC CANCEL REQUEST");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT REQ_NO FROM D_COM_DOC_CANCEL_REQUEST WHERE APPROVED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : DOC. CANCEL REQUEST");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=44 AND DOC_NO='"+rsTmp.getString("REQ_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("REQ_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        

        
        //Module 46
        lblStatus.setText("SERVICE CONTRACT");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT PO_NO FROM D_PUR_PO_HEADER WHERE APPROVED=0 AND PO_TYPE=8 AND CANCELLED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : PO SERVICE CONTRACT");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=46 AND DOC_NO='"+rsTmp.getString("PO_NO")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getString("PO_NO"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }
        
        

        //Module 50
        lblStatus.setText("SUPPLIER UPDATION");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT AMEND_ID FROM D_COM_SUPP_AMEND_MASTER WHERE APPROVED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : SUPPLIER UPDATION");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=50 AND DOC_NO='"+rsTmp.getInt("AMEND_ID")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getInt("AMEND_ID"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }

        
        //Module 51
        lblStatus.setText("ITEM MASTER UPDATION");
        lblStatus.repaint();
        
        rsTmp=data.getResult("SELECT ITEM_ID FROM D_INV_ITEM_MASTER_AMEND WHERE APPROVED=0");
        rsTmp.first();
        if(rsTmp.getRow()>0) {
            aFile.write("Module : ITEM MASTER UPDATION");
            aFile.newLine();
            
            while(!rsTmp.isAfterLast()) {
                rsDoc=data.getResult("SELECT * FROM D_COM_DOC_DATA WHERE MODULE_ID=51 AND DOC_NO='"+rsTmp.getString("ITEM_ID")+"' AND STATUS='W'");
                rsDoc.first();
                
                if(rsDoc.getRow()<=0) {
                    aFile.write(rsTmp.getInt("ITEM_ID"));
                    aFile.newLine();
                }
                rsTmp.next();
            }
        }

        
        lblStatus.setText("Done");
        

        aFile.close();
        
        }
        catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null," Error "+e.getMessage());
        }
        
           };
        }.start();
        
    }
    
}
