/*
 * SelectMIR.java
 *
 * Created on May 12, 2004, 11:11 AM
 */

package EITLERP.Purchase;

/**
 * 
 * @author  nrpithva
 */
/*<APPLET CODE=SelectPO.Class HEIGHT=560 WIDTH=700></APPLET>*/
  
import javax.swing.*;
import java.awt.*;
import java.util.*;
import EITLERP.*;
import javax.swing.table.*;
import javax.swing.event.*;
import java.awt.event.*;

public class SelectServicePO extends javax.swing.JApplet {
    
    private EITLTableModel DataModelL;
    
    private EITLComboModel cmbFromModel;
    
    public boolean Cancelled=true;
    private JDialog aDialog;
    public int ModuleID=46;
    public int POType=8;
    
    private String SelPONo="";
    public clsPOGen SelPO;
       
    private EITLTableModel DataModelS=new EITLTableModel();
    
    public SelectServicePO(){
       initComponents();
       GenerateCombo();
    }
    
    /** Initializes the applet SelectPO */
    public void init() {
        System.gc();
        initComponents();
        GenerateCombo();
      }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        txtPONo = new javax.swing.JTextField();
        cmdShow = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDocNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDocDate = new javax.swing.JTextField();
        txtSuppName = new javax.swing.JTextField();
        txtSuppCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtIntroduction = new javax.swing.JTextField();
        txtPremises = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtServicePeriod = new javax.swing.JTextField();
        txtFrequency = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtNetAmount = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtInWords = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtScope = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtContractDetails = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTerminationTerms = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPaymentTerms = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtServiceReport = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbFromYear = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtToYear = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmdCopy = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSuppCodeH = new javax.swing.JTextField();
        txtSuppNameH = new javax.swing.JTextField();
        cmdGetLastPO = new javax.swing.JButton();
        
        getContentPane().setLayout(null);
        
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Select P.O.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(7, 127, 79, 15);
        
        txtPONo.setNextFocusableComponent(cmdGetLastPO);
        txtPONo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPONoKeyPressed(evt);
            }
        });
        
        getContentPane().add(txtPONo);
        txtPONo.setBounds(96, 124, 106, 19);
        
        cmdShow.setMnemonic('S');
        cmdShow.setText("Show P.O.");
        cmdShow.setNextFocusableComponent(cmdCopy);
        cmdShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdShowActionPerformed(evt);
            }
        });
        
        getContentPane().add(cmdShow);
        cmdShow.setBounds(368, 124, 102, 22);
        
        jPanel4.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(4, 152, 680, 2);
        
        jPanel1.setLayout(null);
        
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setText("P.O. No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(52, 18, 56, 15);
        
        txtDocNo.setBackground(new java.awt.Color(204, 204, 255));
        txtDocNo.setEditable(false);
        jPanel1.add(txtDocNo);
        txtDocNo.setBounds(114, 14, 114, 19);
        
        jLabel3.setText("Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(254, 18, 29, 15);
        
        txtDocDate.setEnabled(false);
        jPanel1.add(txtDocDate);
        txtDocDate.setBounds(290, 16, 100, 19);
        
        txtSuppName.setEditable(false);
        jPanel1.add(txtSuppName);
        txtSuppName.setBounds(178, 50, 212, 19);
        
        txtSuppCode.setEnabled(false);
        jPanel1.add(txtSuppCode);
        txtSuppCode.setBounds(114, 50, 62, 19);
        
        jLabel4.setText("Supplier");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(54, 54, 52, 15);
        
        jLabel41.setText("Subject");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(58, 91, 52, 15);
        
        txtSubject.setEnabled(false);
        jPanel1.add(txtSubject);
        txtSubject.setBounds(116, 89, 505, 21);
        
        jLabel47.setText("Introduction");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(27, 119, 81, 15);
        
        txtIntroduction.setEnabled(false);
        jPanel1.add(txtIntroduction);
        txtIntroduction.setBounds(117, 116, 504, 21);
        
        txtPremises.setEnabled(false);
        jPanel1.add(txtPremises);
        txtPremises.setBounds(116, 143, 504, 21);
        
        jLabel43.setText("Premises");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(41, 146, 72, 15);
        
        jLabel44.setText("Service Period");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(18, 181, 97, 15);
        
        txtServicePeriod.setEnabled(false);
        jPanel1.add(txtServicePeriod);
        txtServicePeriod.setBounds(117, 178, 501, 21);
        
        txtFrequency.setEnabled(false);
        jPanel1.add(txtFrequency);
        txtFrequency.setBounds(117, 205, 500, 21);
        
        jLabel45.setText("Frequency");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(42, 208, 72, 15);
        
        txtNetAmount.setBackground(new java.awt.Color(255, 255, 204));
        txtNetAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNetAmount.setEnabled(false);
        jPanel1.add(txtNetAmount);
        txtNetAmount.setBounds(120, 254, 140, 22);
        
        jLabel46.setText("Contract Value");
        jPanel1.add(jLabel46);
        jLabel46.setBounds(21, 257, 99, 15);
        
        txtInWords.setEnabled(false);
        jPanel1.add(txtInWords);
        txtInWords.setBounds(122, 281, 462, 21);
        
        jTabbedPane1.addTab("P.O. Information", jPanel1);
        
        jPanel2.setLayout(null);
        
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        txtScope.setLineWrap(true);
        txtScope.setWrapStyleWord(true);
        txtScope.setEnabled(false);
        jScrollPane1.setViewportView(txtScope);
        
        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(13, 39, 648, 252);
        
        jLabel6.setText("Scope of Work");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(16, 15, 92, 15);
        
        txtRemarks.setName("REMARKS");
        txtRemarks.setEnabled(false);
        jPanel2.add(txtRemarks);
        txtRemarks.setBounds(66, 320, 464, 19);
        
        jLabel39.setText("Remarks");
        jPanel2.add(jLabel39);
        jLabel39.setBounds(6, 322, 58, 15);
        
        jTabbedPane1.addTab("Item Information", jPanel2);
        
        jPanel3.setLayout(null);
        
        jPanel3.setBorder(new javax.swing.border.EtchedBorder());
        txtContractDetails.setEnabled(false);
        jScrollPane3.setViewportView(txtContractDetails);
        
        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(8, 32, 652, 305);
        
        jLabel7.setText("Contract Details");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(9, 10, 131, 15);
        
        jTabbedPane1.addTab("Other Information", jPanel3);
        
        jPanel6.setLayout(null);
        
        jPanel6.setBorder(new javax.swing.border.EtchedBorder());
        txtTerminationTerms.setEnabled(false);
        jScrollPane4.setViewportView(txtTerminationTerms);
        
        jPanel6.add(jScrollPane4);
        jScrollPane4.setBounds(18, 233, 646, 62);
        
        txtPaymentTerms.setEnabled(false);
        jScrollPane5.setViewportView(txtPaymentTerms);
        
        jPanel6.add(jScrollPane5);
        jScrollPane5.setBounds(10, 32, 649, 61);
        
        jLabel20.setText("Contract Termination Terms");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(16, 214, 177, 15);
        
        txtServiceReport.setEnabled(false);
        jScrollPane7.setViewportView(txtServiceReport);
        
        jPanel6.add(jScrollPane7);
        jScrollPane7.setBounds(13, 125, 647, 73);
        
        jLabel18.setText("Service Report");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(14, 103, 96, 15);
        
        jLabel19.setText("Payment Terms");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(8, 14, 96, 15);
        
        jTabbedPane1.addTab("Terms & Conditions", jPanel6);
        
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(6, 162, 678, 387);
        
        jLabel13.setText("Fin. Year");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(24, 43, 65, 15);
        
        cmbFromYear.setNextFocusableComponent(txtSuppCodeH);
        cmbFromYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFromYearItemStateChanged(evt);
            }
        });
        
        getContentPane().add(cmbFromYear);
        cmbFromYear.setBounds(96, 39, 102, 24);
        
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel14.setText("To");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(206, 43, 24, 14);
        
        txtToYear.setEditable(false);
        getContentPane().add(txtToYear);
        txtToYear.setBounds(230, 39, 102, 19);
        
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("Copy P.O.");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(8, 6, 70, 17);
        
        jPanel5.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(8, 32, 680, 2);
        
        cmdCopy.setBackground(new java.awt.Color(204, 204, 255));
        cmdCopy.setText("Copy");
        cmdCopy.setNextFocusableComponent(cmdCancel);
        cmdCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCopyActionPerformed(evt);
            }
        });
        
        getContentPane().add(cmdCopy);
        cmdCopy.setBounds(594, 42, 80, 25);
        
        cmdCancel.setBackground(new java.awt.Color(204, 204, 255));
        cmdCancel.setText("Cancel");
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });
        
        getContentPane().add(cmdCancel);
        cmdCancel.setBounds(594, 70, 79, 25);
        
        jLabel5.setText("Supplier");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(38, 71, 52, 15);
        
        txtSuppCodeH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSuppCodeHFocusLost(evt);
            }
        });
        txtSuppCodeH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSuppCodeHKeyPressed(evt);
            }
        });
        
        getContentPane().add(txtSuppCodeH);
        txtSuppCodeH.setBounds(98, 70, 62, 19);
        
        txtSuppNameH.setEditable(false);
        getContentPane().add(txtSuppNameH);
        txtSuppNameH.setBounds(162, 70, 212, 19);
        
        cmdGetLastPO.setMnemonic('S');
        cmdGetLastPO.setText("Get Last P.O. No.");
        cmdGetLastPO.setNextFocusableComponent(cmdShow);
        cmdGetLastPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGetLastPOActionPerformed(evt);
            }
        });
        
        getContentPane().add(cmdGetLastPO);
        cmdGetLastPO.setBounds(220, 124, 142, 22);
        
    }//GEN-END:initComponents

    private void cmdGetLastPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGetLastPOActionPerformed
        // TODO add your handling code here:
        String dbURL=clsFinYear.getDBURL(EITLERPGLOBAL.gCompanyID,Integer.parseInt((String)cmbFromYear.getSelectedItem()));        
        String LastPONo=clsPOGen.getLastPOEx(EITLERPGLOBAL.gCompanyID, POType, txtSuppCodeH.getText(),"",dbURL);
        txtPONo.setText(LastPONo);
    }//GEN-LAST:event_cmdGetLastPOActionPerformed

    private void txtSuppCodeHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuppCodeHKeyPressed
        // TODO add your handling code here:
        //=========== Supplier List ===============
        if(evt.getKeyCode()==112) //F1 Key pressed
        {
            LOV aList=new LOV();
            
            aList.SQL="SELECT SUPPLIER_CODE,SUPP_NAME FROM D_COM_SUPP_MASTER WHERE COMPANY_ID="+EITLERPGLOBAL.gCompanyID+" AND BLOCKED='N' AND APPROVED=1 ORDER BY SUPP_NAME";
            aList.ReturnCol=1;
            aList.ShowReturnCol=true;
            aList.DefaultSearchOn=2;
            
            if(aList.ShowLOV()) {
                txtSuppCodeH.setText(aList.ReturnVal);
                txtSuppNameH.setText(clsSupplier.getSupplierName(EITLERPGLOBAL.gCompanyID,aList.ReturnVal));
            }
        }
        //=========================================
    }//GEN-LAST:event_txtSuppCodeHKeyPressed

    private void txtSuppCodeHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSuppCodeHFocusLost
        // TODO add your handling code here:
        if(!txtSuppCodeH.getText().trim().equals("")) {
            txtSuppNameH.setText(clsSupplier.getSupplierName(EITLERPGLOBAL.gCompanyID, txtSuppCodeH.getText()));
        }
    }//GEN-LAST:event_txtSuppCodeHFocusLost

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        // TODO add your handling code here:
        Cancelled=true;
        aDialog.dispose();
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCopyActionPerformed
        // TODO add your handling code here:
        if(txtPONo.getText().trim().equals(""))
        {
            Cancelled=true;
        }
        else
        {
           Cancelled=false;
        }
        aDialog.dispose();
    }//GEN-LAST:event_cmdCopyActionPerformed

    private void cmbFromYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFromYearItemStateChanged
        // TODO add your handling code here:
        int ToYear=Integer.parseInt((String)cmbFromYear.getSelectedItem())+1;
        txtToYear.setText(Integer.toString(ToYear));
    }//GEN-LAST:event_cmbFromYearItemStateChanged

    private void txtPONoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPONoKeyPressed
        // TODO add your handling code here:
        //=========== Supplier List ===============
        if(evt.getKeyCode()==112) //F1 Key pressed
        {
            
            POList aList=new POList();
            
            aList.POType=POType;
            aList.FinYear=Integer.parseInt((String)cmbFromYear.getSelectedItem());
                
            if(txtSuppCodeH.getText().trim().equals(""))
            {
                aList.SuppID="";
            }
            else
            {
                aList.SuppID=txtSuppCodeH.getText();
            }
            
            aList.ReturnCol=1;
            aList.ShowReturnCol=true;
            aList.DefaultSearchOn=1;
            
            if(aList.ShowLOV()) {
                txtPONo.setText(aList.ReturnVal);
            }
        }
        //=========================================        
    }//GEN-LAST:event_txtPONoKeyPressed

    private void cmdShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdShowActionPerformed
        // TODO add your handling code here:
        SelPONo=txtPONo.getText();
        String dbURL=clsFinYear.getDBURL(EITLERPGLOBAL.gCompanyID,Integer.parseInt((String)cmbFromYear.getSelectedItem()));
        
        String docStatus=clsPOGen.getDocStatus(EITLERPGLOBAL.gCompanyID,SelPONo,dbURL);
        
        if(!docStatus.equals(""))
        {
          JOptionPane.showMessageDialog(null,docStatus);
        }
        
        SelPO=new clsPOGen();
        clsPOGen ObjPO=new clsPOGen();
        SelPO=(clsPOGen)ObjPO.getObject(EITLERPGLOBAL.gCompanyID,SelPONo,dbURL,POType);
        
        int POType=clsPOGen.getPOType(EITLERPGLOBAL.gCompanyID, SelPONo);
        
        DisplayData();
    }//GEN-LAST:event_cmdShowActionPerformed
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbFromYear;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdCopy;
    private javax.swing.JButton cmdGetLastPO;
    private javax.swing.JButton cmdShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtContractDetails;
    private javax.swing.JTextField txtDocDate;
    private javax.swing.JTextField txtDocNo;
    private javax.swing.JTextField txtFrequency;
    private javax.swing.JTextField txtInWords;
    private javax.swing.JTextField txtIntroduction;
    private javax.swing.JTextField txtNetAmount;
    private javax.swing.JTextField txtPONo;
    private javax.swing.JTextArea txtPaymentTerms;
    private javax.swing.JTextField txtPremises;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextArea txtScope;
    private javax.swing.JTextField txtServicePeriod;
    private javax.swing.JTextArea txtServiceReport;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtSuppCode;
    private javax.swing.JTextField txtSuppCodeH;
    private javax.swing.JTextField txtSuppName;
    private javax.swing.JTextField txtSuppNameH;
    private javax.swing.JTextArea txtTerminationTerms;
    private javax.swing.JTextField txtToYear;
    // End of variables declaration//GEN-END:variables
    

private void DisplayData()
{
    
    String dbURL=clsFinYear.getDBURL(EITLERPGLOBAL.gCompanyID,Integer.parseInt((String)cmbFromYear.getSelectedItem()));
    
    txtDocNo.setText((String)SelPO.getAttribute("PO_NO").getObj());
    txtDocDate.setText(EITLERPGLOBAL.formatDate((String)SelPO.getAttribute("PO_DATE").getObj()));
    txtSuppCode.setText((String)SelPO.getAttribute("SUPP_ID").getObj());
    txtSuppName.setText(clsSupplier.getSupplierName(EITLERPGLOBAL.gCompanyID,txtSuppCode.getText(),dbURL));

            if(!clsSupplier.IsValidSuppCode(EITLERPGLOBAL.gCompanyID, (String)SelPO.getAttribute("SUPP_ID").getObj())) {
                txtSuppName.setText((String)SelPO.getAttribute("SUPP_NAME").getObj());
            }
            else {
                txtSuppName.setText(clsSupplier.getSupplierName(EITLERPGLOBAL.gCompanyID, txtSuppCode.getText()));
            }
            

            txtSubject.setText((String)SelPO.getAttribute("SUBJECT").getObj());
            txtRemarks.setText((String)SelPO.getAttribute("REMARKS").getObj());
            
            
            txtIntroduction.setText((String)SelPO.getAttribute("COVERING_TEXT").getObj());
            
            txtPremises.setText((String)SelPO.getAttribute("PREMISES_TYPE").getObj());
            txtServicePeriod.setText((String)SelPO.getAttribute("SERVICE_PERIOD").getObj());
            txtFrequency.setText((String)SelPO.getAttribute("SERVICE_FREQUENCY").getObj());
            txtNetAmount.setText(Double.toString(SelPO.getAttribute("NET_AMOUNT").getVal()));
            txtScope.setText((String)SelPO.getAttribute("SCOPE").getObj());
            txtContractDetails.setText((String)SelPO.getAttribute("CONTRACT_DETAILS").getObj());
            txtPaymentTerms.setText((String)SelPO.getAttribute("PAYMENT_TERM").getObj());
            txtServiceReport.setText((String)SelPO.getAttribute("SERVICE_REPORT").getObj());
            txtInWords.setText((String)SelPO.getAttribute("AMOUNT_IN_WORDS").getObj());
            txtTerminationTerms.setText((String)SelPO.getAttribute("TERMINATION_TERMS").getObj());
    
            
}

    //Recurses through the hierarchy of classes
    //until it finds Frame
    private Frame findParentFrame(JApplet pApplet) {
        Container c = (Container) pApplet;
        while(c != null) {
            if (c instanceof Frame)
                return (Frame)c;
            
            c = c.getParent();
        }
        return (Frame)null;
    }

public boolean ShowDialog() {
        try {
                 
            setSize(700,560);
            
            Frame f=findParentFrame(this);
            
            aDialog=new JDialog(f,"Copy Purchase Order",true);
            
            aDialog.getContentPane().add("Center",this);
            Dimension appletSize = this.getSize();
            aDialog.setSize(appletSize);
            aDialog.setResizable(false);
            
            //Place it to center of the screen
            Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
            aDialog.setLocation((int)(screenSize.width-appletSize.getWidth())/2,(int)(screenSize.height-appletSize.getHeight())/2);
            
            aDialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
            aDialog.show();
        }
        catch(Exception e) {
        }
        return !Cancelled;
    }    

private void GenerateCombo()
{
        HashMap List=new HashMap();
        
        cmbFromModel=new EITLComboModel();
        cmbFromYear.setModel(cmbFromModel);
        cmbFromYear.removeAllItems();
        
        List=clsFinYear.getList(" WHERE COMPANY_ID="+EITLERPGLOBAL.gCompanyID);
        
        for(int i=1;i<=List.size();i++) {
            clsFinYear ObjYear =(clsFinYear) List.get(Integer.toString(i));
            
            ComboData cmbData=new ComboData();
            cmbData.Text=Integer.toString((int)ObjYear.getAttribute("YEAR_FROM").getVal());
            cmbData.Code=(int)ObjYear.getAttribute("YEAR_FROM").getVal();
            cmbData.strCode =Integer.toString((int)ObjYear.getAttribute("YEAR_FROM").getVal());
            cmbFromModel.addElement(cmbData);
        }
}



}
