/*
 * SelectMIR.java
 *
 * Created on May 12, 2004, 11:11 AM
 */

package EITLERP.Stores;
 
/** 
 * 
 * @author  nrpithva
 */
/*<APPLET CODE=SelectSTM2.Class HEIGHT=400 WIDTH=700></APPLET>*/

import javax.swing.*;
import java.awt.*;
import java.util.*;
import EITLERP.*;
import javax.swing.table.*;
import javax.swing.event.*;
import java.awt.event.*;
 
public class SelectSTM2 extends javax.swing.JApplet {
    
    private EITLTableModel DataModel;
    private EITLTableCellRenderer Rend=new EITLTableCellRenderer();

    public boolean Cancelled=true;
    public HashMap colSelItems=new HashMap();
    private JDialog aDialog;
    public int ModuleID=0;
    private String SelSTMNo="";
    public int STMType=1;
    
    public boolean CopyHeader=true;
    public clsSTMRaw ObjSTM;
    public clsSTMGen ObjSTMGen;
    //public String sdbURL="";

    private EITLComboModel cmbDeptModel;
    private int SelDeptID=0;
    
    private String dbURL="";
    public int SelCompanyID=0;
    public int SelFromYear=0;

    private EITLComboModel cmbCompanyModel;
    private EITLComboModel cmbFromModel;
    
   public SelectSTM2()
    {
       setSize(700,430);
       initComponents();
       GenerateCombo();
       FormatGrid();
       int DeptID=clsUser.getDeptID(EITLERPGLOBAL.gCompanyID, EITLERPGLOBAL.gUserID);
       EITLERPGLOBAL.setComboIndex(cmbDept,DeptID);
       EITLERPGLOBAL.setComboIndex(cmbFromYear,EITLERPGLOBAL.FinYearFrom);
       txtGRNNo.requestFocus();
    }
    
    /** Initializes the applet SelectMIR */
    /*public void init() {
        initComponents();
        FormatGrid();
        GenerateCombo();
       int DeptID=clsUser.getDeptID(EITLERPGLOBAL.gCompanyID, EITLERPGLOBAL.gUserID);
       EITLERPGLOBAL.setComboIndex(cmbDept,DeptID);
       txtGRNNo.requestFocus();
    }*/
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGRNNo = new javax.swing.JTextField();
        cmdShow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cmdOK = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        cmdSelectAll = new javax.swing.JButton();
        cmdClearAll = new javax.swing.JButton();
        chkCopyHeader = new javax.swing.JCheckBox();
        cmbDept = new javax.swing.JComboBox();
        chkDept = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cmbCompany = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbFromYear = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtToYear = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Select STM Items from the List");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 212, 15);

        jLabel2.setDisplayedMnemonic('M');
        jLabel2.setLabelFor(txtGRNNo);
        jLabel2.setText("STM No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(15, 128, 56, 15);

        txtGRNNo.setNextFocusableComponent(cmdShow);
        txtGRNNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGRNNoKeyPressed(evt);
            }
        });

        getContentPane().add(txtGRNNo);
        txtGRNNo.setBounds(77, 126, 106, 19);

        cmdShow.setMnemonic('S');
        cmdShow.setText("Show Items");
        cmdShow.setNextFocusableComponent(Table);
        cmdShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdShowActionPerformed(evt);
            }
        });

        getContentPane().add(cmdShow);
        cmdShow.setBounds(191, 126, 110, 22);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setNextFocusableComponent(cmdSelectAll);
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 177, 660, 174);

        jPanel4.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(5, 159, 662, 6);

        cmdOK.setMnemonic('O');
        cmdOK.setText("OK");
        cmdOK.setNextFocusableComponent(cmdCancel);
        cmdOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOKActionPerformed(evt);
            }
        });

        getContentPane().add(cmdOK);
        cmdOK.setBounds(502, 358, 78, 25);

        cmdCancel.setMnemonic('C');
        cmdCancel.setText("Cancel");
        cmdCancel.setNextFocusableComponent(cmdOK);
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        getContentPane().add(cmdCancel);
        cmdCancel.setBounds(586, 358, 79, 25);

        cmdSelectAll.setMnemonic('A');
        cmdSelectAll.setText("Select All");
        cmdSelectAll.setNextFocusableComponent(cmdClearAll);
        cmdSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSelectAllActionPerformed(evt);
            }
        });

        getContentPane().add(cmdSelectAll);
        cmdSelectAll.setBounds(16, 360, 106, 25);

        cmdClearAll.setMnemonic('l');
        cmdClearAll.setText("Clear All");
        cmdClearAll.setNextFocusableComponent(cmdOK);
        cmdClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClearAllActionPerformed(evt);
            }
        });

        getContentPane().add(cmdClearAll);
        cmdClearAll.setBounds(134, 360, 102, 25);

        chkCopyHeader.setMnemonic('C');
        chkCopyHeader.setSelected(true);
        chkCopyHeader.setText("Copy Header Information");
        getContentPane().add(chkCopyHeader);
        chkCopyHeader.setBounds(462, 10, 210, 23);

        cmbDept.setEnabled(false);
        getContentPane().add(cmbDept);
        cmbDept.setBounds(77, 91, 224, 24);

        chkDept.setText("Dept");
        chkDept.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkDeptStateChanged(evt);
            }
        });

        getContentPane().add(chkDept);
        chkDept.setBounds(10, 92, 63, 23);

        jLabel3.setDisplayedMnemonic('I');
        jLabel3.setText("Company");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(8, 51, 66, 15);

        cmbCompany.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCompanyItemStateChanged(evt);
            }
        });

        getContentPane().add(cmbCompany);
        cmbCompany.setBounds(79, 47, 221, 24);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel6.setText("Year");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(341, 50, 38, 14);

        cmbFromYear.setOpaque(false);
        cmbFromYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFromYearItemStateChanged(evt);
            }
        });

        getContentPane().add(cmbFromYear);
        cmbFromYear.setBounds(387, 46, 102, 24);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 11));
        jLabel7.setText("To");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(496, 51, 24, 14);

        txtToYear.setEditable(false);
        txtToYear.setOpaque(false);
        getContentPane().add(txtToYear);
        txtToYear.setBounds(519, 48, 102, 19);

    }//GEN-END:initComponents

    private void cmbFromYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFromYearItemStateChanged
        // TODO add your handling code here:
        int ToYear=Integer.parseInt((String)cmbFromYear.getSelectedItem())+1;
        txtToYear.setText(Integer.toString(ToYear));
    }//GEN-LAST:event_cmbFromYearItemStateChanged

    private void cmbCompanyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCompanyItemStateChanged
        // TODO add your handling code here:
        SelCompanyID=EITLERPGLOBAL.getComboCode(cmbCompany);
        GenerateYearCombo();
        GenerateDeptCombo();
    }//GEN-LAST:event_cmbCompanyItemStateChanged

    private void chkDeptStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkDeptStateChanged
        // TODO add your handling code here:
        if(chkDept.isSelected())
        {
            cmbDept.setEnabled(true);
        }
        else
        {
            cmbDept.setEnabled(false);
        }
    }//GEN-LAST:event_chkDeptStateChanged

    private void txtGRNNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGRNNoKeyPressed
        // TODO add your handling code here:
        //=========== Supplier List ===============
        if(evt.getKeyCode()==112) //F1 Key pressed
        {
            SelCompanyID=EITLERPGLOBAL.getComboCode(cmbCompany);
            int FromYear=EITLERPGLOBAL.getComboCode(cmbFromYear);
            
            LOV aList=new LOV();
            aList.UseSpecifiedConn=true;
            aList.dbURL=clsFinYear.getDBURL(SelCompanyID, FromYear);
            String FromDate = FromYear + "-04-01";
            String ToDate = txtToYear.getText().trim() + "-03-31";
            if(chkDept.isSelected())
            {
              aList.SQL="SELECT DISTINCT(D_INV_STM_HEADER.STM_NO) AS STM_NO,DATE_FORMAT(STM_DATE,'%d/%m/%Y') AS DATE,DEPT_DESC AS DEPT FROM D_INV_STM_HEADER,D_INV_STM_DETAIL,D_COM_USER_MASTER,D_COM_DEPT_MASTER WHERE D_INV_STM_HEADER.COMPANY_ID=D_INV_STM_DETAIL.COMPANY_ID AND D_INV_STM_HEADER.STM_NO=D_INV_STM_DETAIL.STM_NO AND D_INV_STM_HEADER.STM_TYPE=D_INV_STM_DETAIL.STM_TYPE  AND D_INV_STM_DETAIL.RECEIVED_QTY<D_INV_STM_DETAIL.QTY AND D_INV_STM_HEADER.APPROVED=1 AND D_INV_STM_HEADER.CREATED_BY=D_COM_USER_MASTER.USER_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_USER_MASTER.COMPANY_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_DEPT_MASTER.COMPANY_ID AND D_COM_USER_MASTER.DEPT_ID=D_COM_DEPT_MASTER.DEPT_ID AND D_COM_USER_MASTER.DEPT_ID="+SelDeptID+" AND  D_INV_STM_HEADER.STM_TYPE="+STMType+" AND CANCELLED=0 AND STM_DATE >= '"+FromDate+"' AND STM_DATE <= '"+ToDate+"' ";  
            }
            else
            {
              aList.SQL="SELECT DISTINCT(D_INV_STM_HEADER.STM_NO) AS STM_NO,DATE_FORMAT(STM_DATE,'%d/%m/%Y') AS DATE,DEPT_DESC AS DEPT FROM D_INV_STM_HEADER,D_INV_STM_DETAIL,D_COM_USER_MASTER,D_COM_DEPT_MASTER WHERE D_INV_STM_HEADER.COMPANY_ID=D_INV_STM_DETAIL.COMPANY_ID AND D_INV_STM_HEADER.STM_NO=D_INV_STM_DETAIL.STM_NO AND D_INV_STM_HEADER.STM_TYPE=D_INV_STM_DETAIL.STM_TYPE  AND D_INV_STM_DETAIL.RECEIVED_QTY<D_INV_STM_DETAIL.QTY AND D_INV_STM_HEADER.APPROVED=1 AND D_INV_STM_HEADER.CREATED_BY=D_COM_USER_MASTER.USER_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_USER_MASTER.COMPANY_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_DEPT_MASTER.COMPANY_ID AND D_COM_USER_MASTER.DEPT_ID=D_COM_DEPT_MASTER.DEPT_ID  AND D_INV_STM_HEADER.STM_TYPE="+STMType+" AND CANCELLED=0 AND STM_DATE >= '"+FromDate+"' AND STM_DATE <= '"+ToDate+"' ";    
            }
            
            System.out.println(aList.SQL);
            
            aList.ReturnCol=1;
            aList.ShowReturnCol=true;
            aList.DefaultSearchOn=1;
            
            if(aList.ShowLOV()) {
                txtGRNNo.setText(aList.ReturnVal);
            }
        }
        //=========================================        
    }//GEN-LAST:event_txtGRNNoKeyPressed

    private void cmdClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClearAllActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<Table.getRowCount();i++)
        {
           DataModel.setValueAt(Boolean.valueOf(false), i, 0); 
        }
    }//GEN-LAST:event_cmdClearAllActionPerformed

    private void cmdSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSelectAllActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<Table.getRowCount();i++)
        {
           DataModel.setValueAt(Boolean.valueOf(true), i, 0); 
        }
    }//GEN-LAST:event_cmdSelectAllActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        // TODO add your handling code here:
        Cancelled=true;
        aDialog.dispose();
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOKActionPerformed
        // TODO add your handling code here:
        if(Table.getRowCount()<=0) {
            Cancelled=true;
        }
        else {
            SetList();
            Cancelled=false;
        }
        aDialog.dispose();
    }//GEN-LAST:event_cmdOKActionPerformed

    private void cmdShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdShowActionPerformed
        // TODO add your handling code here:
        
        SelSTMNo=txtGRNNo.getText();
        SelCompanyID=EITLERPGLOBAL.getComboCode(cmbCompany);
        SelFromYear=EITLERPGLOBAL.getComboCode(cmbFromYear);
        String dbURL=clsFinYear.getDBURL(SelCompanyID,SelFromYear);
        String FromDate = SelFromYear + "-04-01";
        String ToDate = txtToYear.getText().trim() + "-03-31";
            
        String SQL ="";
        if(chkDept.isSelected())
        {
          SQL="SELECT DISTINCT(D_INV_STM_HEADER.STM_NO) AS STM_NO,DATE_FORMAT(STM_DATE,'%d/%m/%Y') AS DATE,DEPT_DESC AS DEPT FROM D_INV_STM_HEADER,D_INV_STM_DETAIL,D_COM_USER_MASTER,D_COM_DEPT_MASTER WHERE D_INV_STM_HEADER.COMPANY_ID=D_INV_STM_DETAIL.COMPANY_ID AND D_INV_STM_HEADER.STM_NO=D_INV_STM_DETAIL.STM_NO AND D_INV_STM_HEADER.STM_TYPE=D_INV_STM_DETAIL.STM_TYPE  AND D_INV_STM_DETAIL.RECEIVED_QTY<D_INV_STM_DETAIL.QTY AND D_INV_STM_HEADER.APPROVED=1 AND D_INV_STM_HEADER.CREATED_BY=D_COM_USER_MASTER.USER_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_USER_MASTER.COMPANY_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_DEPT_MASTER.COMPANY_ID AND D_COM_USER_MASTER.DEPT_ID=D_COM_DEPT_MASTER.DEPT_ID AND D_COM_USER_MASTER.DEPT_ID="+SelDeptID+" AND  D_INV_STM_HEADER.STM_TYPE="+STMType+" AND CANCELLED=0 AND STM_DATE >= '"+FromDate+"' AND STM_DATE <= '"+ToDate+"' AND D_INV_STM_HEADER.STM_NO='"+txtGRNNo.getText().trim()+"' ";  
        }
        else
        {
          SQL="SELECT DISTINCT(D_INV_STM_HEADER.STM_NO) AS STM_NO,DATE_FORMAT(STM_DATE,'%d/%m/%Y') AS DATE,DEPT_DESC AS DEPT FROM D_INV_STM_HEADER,D_INV_STM_DETAIL,D_COM_USER_MASTER,D_COM_DEPT_MASTER WHERE D_INV_STM_HEADER.COMPANY_ID=D_INV_STM_DETAIL.COMPANY_ID AND D_INV_STM_HEADER.STM_NO=D_INV_STM_DETAIL.STM_NO AND D_INV_STM_HEADER.STM_TYPE=D_INV_STM_DETAIL.STM_TYPE  AND D_INV_STM_DETAIL.RECEIVED_QTY<D_INV_STM_DETAIL.QTY AND D_INV_STM_HEADER.APPROVED=1 AND D_INV_STM_HEADER.CREATED_BY=D_COM_USER_MASTER.USER_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_USER_MASTER.COMPANY_ID AND D_INV_STM_HEADER.COMPANY_ID=D_COM_DEPT_MASTER.COMPANY_ID AND D_COM_USER_MASTER.DEPT_ID=D_COM_DEPT_MASTER.DEPT_ID  AND D_INV_STM_HEADER.STM_TYPE="+STMType+" AND CANCELLED=0 AND STM_DATE >= '"+FromDate+"' AND STM_DATE <= '"+ToDate+"' AND D_INV_STM_HEADER.STM_NO='"+txtGRNNo.getText().trim()+"' ";    
        }
        if (! data.IsRecordExist(SQL,dbURL)) {
            JOptionPane.showMessageDialog(null,"STM No is Invalid");  
            return;
        }
        String docStatus=clsSTMGen.getDocStatus(SelSTMNo,dbURL);
        
        if(!docStatus.trim().equals(""))
        {
          JOptionPane.showMessageDialog(null,docStatus);  
          return;
        }
        
        FormatGrid();
        GenerateGrid();
        
        if(Table.getRowCount()==0&&docStatus.trim().equals(""))
        {
          JOptionPane.showMessageDialog(null,"No pending items found");
        }
    }//GEN-LAST:event_cmdShowActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JCheckBox chkCopyHeader;
    private javax.swing.JCheckBox chkDept;
    private javax.swing.JComboBox cmbCompany;
    private javax.swing.JComboBox cmbDept;
    private javax.swing.JComboBox cmbFromYear;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdClearAll;
    private javax.swing.JButton cmdOK;
    private javax.swing.JButton cmdSelectAll;
    private javax.swing.JButton cmdShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtGRNNo;
    private javax.swing.JTextField txtToYear;
    // End of variables declaration//GEN-END:variables
    
private void FormatGrid()    
{
        DataModel=new EITLTableModel();
        
        Table.removeAll();
        
        Table.setModel(DataModel);
        Table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        for(int i=1;i<=12;i++)
        {
            DataModel.SetReadOnly(i);
        }
        
        //Add Columns to it
        DataModel.addColumn(""); //0 Selection
        DataModel.addColumn("Sr.");//1
        DataModel.addColumn("Item ID");//2
        DataModel.addColumn("Item Name");//3
        DataModel.addColumn("BOE No.");//7
        DataModel.addColumn("Qty");//4
        DataModel.addColumn("Unit");//6
        DataModel.addColumn("Rate");//6
        DataModel.addColumn("Net Amount");//6
        DataModel.addColumn("Description");//6
        DataModel.addColumn("Remarks");//6
        DataModel.addColumn("Received Qty.");//6
        
        Rend.setCustomComponent(0,"CheckBox");
        Table.getColumnModel().getColumn(0).setCellRenderer(Rend);
        Table.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(new JCheckBox()));
}

private void SetList()
{
    int SrNo=0;
    HashMap List=new HashMap();
    
    colSelItems.clear();
    
    SelCompanyID=EITLERPGLOBAL.getComboCode(cmbCompany);
    SelFromYear=EITLERPGLOBAL.getComboCode(cmbFromYear);
    
    String dbURL=clsFinYear.getDBURL(SelCompanyID,SelFromYear);
    String STMNo=txtGRNNo.getText();    
      
    if(STMType==1) //General
    {
       clsSTMGen tmpObj=new clsSTMGen();
       ObjSTMGen=(clsSTMGen)tmpObj.getObject(SelCompanyID, STMNo,dbURL);
    }
    else //Raw Material
    {
       clsSTMRaw tmpObj=new clsSTMRaw();
       ObjSTM=(clsSTMRaw)tmpObj.getObject(SelCompanyID, STMNo,dbURL);
    }
    
    CopyHeader=chkCopyHeader.isSelected();
    
    
    List=clsSTMGen.getSTMItemList(EITLERPGLOBAL.gCompanyID, STMNo,false,STMType,dbURL);    
    //Scan the Table to get selected items
    for(int i=1;i<=List.size();i++)
    {
       clsSTMRawItem ObjItem=(clsSTMRawItem)List.get(Integer.toString(i));
       SrNo=(int)ObjItem.getAttribute("SR_NO").getVal();
       
        //Search in the table for SrNo.
       for(int j=0;j<Table.getRowCount();j++)
       {
           if(Integer.parseInt(Table.getValueAt(j, 1).toString())==SrNo) 
           {
             if(Table.getValueAt(j,0).toString().equals("true"))  
             {
               //Selected Item  
               colSelItems.put(Integer.toString(colSelItems.size()+1),ObjItem);
             }
           }
       }
    }
}

private void GenerateGrid()
{
    HashMap List=new HashMap();
    String STMNo=txtGRNNo.getText();
    
    SelCompanyID=EITLERPGLOBAL.getComboCode(cmbCompany);
    SelFromYear=EITLERPGLOBAL.getComboCode(cmbFromYear);
    String dbURL=clsFinYear.getDBURL(SelCompanyID,SelFromYear);
    
    if(!STMNo.equals(""))
    {
       //List=clsSTMRaw.getSTMItemList(EITLERPGLOBAL.gCompanyID,STMNo,false,STMType,dbURL);
        List=clsSTMGen.getSTMItemList(EITLERPGLOBAL.gCompanyID,STMNo,false,STMType,dbURL);
       
       for(int i=1;i<=List.size();i++)
       {
           clsSTMRawItem ObjItem=(clsSTMRawItem)List.get(Integer.toString(i));
           HashMap colLot=ObjItem.colSTMLot;
           
           Object[] rowData=new Object[12];
           
           rowData[0]=Boolean.valueOf(true); //By default not selected
           rowData[1]=Integer.toString((int)ObjItem.getAttribute("SR_NO").getVal());
           rowData[2]=(String)ObjItem.getAttribute("ITEM_ID").getObj();
           rowData[3]=clsItem.getItemName(EITLERPGLOBAL.gCompanyID,(String)ObjItem.getAttribute("ITEM_ID").getObj());
           rowData[4]=(String) ObjItem.getAttribute("BOE_NO").getObj();
           rowData[5]=Double.toString(ObjItem.getAttribute("QTY").getVal());
           rowData[6]=clsParameter.getParaDescription(EITLERPGLOBAL.gCompanyID, "UNIT", (int)ObjItem.getAttribute("UNIT").getVal());
           rowData[7]=Double.toString(ObjItem.getAttribute("RATE").getVal());
           rowData[8]=Double.toString(ObjItem.getAttribute("NET_AMOUNT").getVal());
           rowData[9]=(String) ObjItem.getAttribute("STM_DESC").getObj();
           rowData[10]=(String) ObjItem.getAttribute("REMARKS").getObj();
           rowData[11]=Double.toString(ObjItem.getAttribute("RECEIVED_QTY").getVal());
           
           DataModel.addRow(rowData);
           
           //Set the Collection
           DataModel.SetUserObject(Table.getRowCount()-1, colLot);
       }
    }
    
}

    //Recurses through the hierarchy of classes
    //until it finds Frame
    private Frame findParentFrame(JApplet pApplet) {
        Container c = (Container) pApplet;
        while(c != null) {
            if (c instanceof Frame)
                return (Frame)c;
            
            c = c.getParent();
        }
        return (Frame)null;
    }

public boolean ShowList() {
        try {
            FormatGrid();
                 
            setSize(700,430);
            
            Frame f=findParentFrame(this);
            
            aDialog=new JDialog(f,"Select STM Items",true);
            
            aDialog.getContentPane().add("Center",this);
            Dimension appletSize = this.getSize();
            aDialog.setSize(appletSize);
            aDialog.setResizable(false);
            
            //Place it to center of the screen
            Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
            aDialog.setLocation((int)(screenSize.width-appletSize.getWidth())/2,(int)(screenSize.height-appletSize.getHeight())/2);
            
            aDialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
            EITLERPGLOBAL.setComboIndex(cmbFromYear,EITLERPGLOBAL.FinYearFrom);
            aDialog.show();
        }
        catch(Exception e) {
        }
        return !Cancelled;
    }    


private void GenerateCombo()
{
    HashMap List=new HashMap();
    String strCondition="";
    
        
        clsCompany ObjCompany;
        
        cmbCompanyModel=new EITLComboModel();
        cmbCompany.setModel(cmbCompanyModel);
        cmbCompany.removeAllItems();  //Clearing previous contents
        
        List=clsCompany.getList("");
        
        for(int i=1;i<=List.size();i++) {
            ObjCompany=(clsCompany) List.get(Integer.toString(i));
            
            ComboData aData=new ComboData();
            
            aData.Text=(String)ObjCompany.getAttribute("COMPANY_NAME").getObj();
            aData.Code=(long)ObjCompany.getAttribute("COMPANY_ID").getVal();
            cmbCompanyModel.addElement(aData);
            
        }
        
        SelCompanyID=EITLERPGLOBAL.getComboCode(cmbCompany);
        GenerateYearCombo();
        GenerateDeptCombo();
}


private void GenerateDeptCombo()
{
    HashMap List=new HashMap();
    String strCondition="";

    dbURL=clsFinYear.getDBURL(SelCompanyID,EITLERPGLOBAL.getComboCode(cmbFromYear));
    
        //----- Generate cmbType ------- //
        cmbDeptModel=new EITLComboModel();
        cmbDept.removeAllItems();
        cmbDept.setModel(cmbDeptModel);
        
        strCondition=" WHERE COMPANY_ID="+SelCompanyID+" ";
        
        List=clsDepartment.getList(strCondition,dbURL);
        for(int i=1;i<=List.size();i++) {
            clsDepartment ObjDept=(clsDepartment) List.get(Integer.toString(i));
            ComboData aData=new ComboData();
            aData.Code=(int) ObjDept.getAttribute("DEPT_ID").getVal();
            aData.Text=(String)ObjDept.getAttribute("DEPT_DESC").getObj();
            aData.strCode="";
            cmbDeptModel.addElement(aData);
        }
        //------------------------------ //
    
}


    private void GenerateYearCombo() {
        HashMap List=new HashMap();

        cmbFromModel=new EITLComboModel();
        cmbFromYear.setModel(cmbFromModel);
        cmbFromYear.removeAllItems();
        
        List=clsFinYear.getList(" WHERE COMPANY_ID="+SelCompanyID);
        
        for(int i=1;i<=List.size();i++) {
            clsFinYear ObjYear =(clsFinYear) List.get(Integer.toString(i));
            
            ComboData cmbData=new ComboData();
            cmbData.Text=Integer.toString((int)ObjYear.getAttribute("YEAR_FROM").getVal());
            cmbData.Code=(int)ObjYear.getAttribute("YEAR_FROM").getVal();
            cmbData.strCode =Integer.toString((int)ObjYear.getAttribute("YEAR_FROM").getVal());
            cmbFromModel.addElement(cmbData);
        }
    }


}
