/*
 * frmFindFeltPackingSlip.java
 * This form is used for searching  the details of Felt Packing
 * 
 * Created on July 19, 2013, 5:17 PM
 */

package EITLERP.FeltSales.SalesReturns;
/**
 *
 * @author  Vivek Kumar
 */


import EITLERP.FeltSales.GroupMaster.*;
import EITLERP.EITLERPGLOBAL;


public class frmFindFeltSalesReturns extends javax.swing.JApplet {
    
    public boolean Cancelled=true;
    public String stringFindQuery="";   
   
    public void init() {
        System.gc();
        setSize(350,220);
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdFind = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtgroupcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpartycode = new javax.swing.JTextField();
        txtpieceno = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Find Felt Sales Returns");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 7, 190, 15);

        cmdFind.setMnemonic('F');
        cmdFind.setText("Find");
        cmdFind.setToolTipText("Find Packing Details by press ALT+F");
        cmdFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdFind.setMargin(new java.awt.Insets(0, 14, 0, 14));
        cmdFind.setNextFocusableComponent(cmdCancel);
        cmdFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFindActionPerformed(evt);
            }
        });
        getContentPane().add(cmdFind);
        cmdFind.setBounds(260, 30, 70, 25);

        cmdCancel.setText("Cancel");
        cmdCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCancel);
        cmdCancel.setBounds(260, 60, 70, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setDisplayedMnemonic('G');
        jLabel2.setLabelFor(txtgroupcode);
        jLabel2.setText("Piece No");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 15);
        jPanel1.add(txtgroupcode);
        txtgroupcode.setBounds(90, 10, 130, 19);

        jLabel3.setDisplayedMnemonic('G');
        jLabel3.setLabelFor(txtgroupcode);
        jLabel3.setText("Doc No");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 60, 15);

        jLabel4.setDisplayedMnemonic('G');
        jLabel4.setLabelFor(txtgroupcode);
        jLabel4.setText("Party Code");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 40, 90, 15);
        jPanel1.add(txtpartycode);
        txtpartycode.setBounds(110, 40, 110, 19);
        jPanel1.add(txtpieceno);
        txtpieceno.setBounds(110, 70, 110, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 240, 140);
    }// </editor-fold>//GEN-END:initComponents
        
    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        stringFindQuery="";
        Cancelled=true;
        getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdCancelActionPerformed
    
    private void cmdFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFindActionPerformed
        Cancelled=false;
        
        String groupcode = txtgroupcode.getText();
        String partycode = txtpartycode.getText().trim();
        String pieceno = txtpieceno.getText().trim();
           
        
        if(!groupcode.equals("")) {
            stringFindQuery=" AND DOC_NO ='"+ groupcode +"' ";
        }
        
        if(!partycode.equals("")) {
            stringFindQuery=" AND DOC_NO IN (SELECT DISTINCT DOC_NO FROM PRODUCTION.FELT_SALES_RETURNS_DETAIL WHERE PARTY_CODE ='"+ partycode +"') ";
        }
        
        if(!pieceno.equals("")) {
            stringFindQuery=" AND DOC_NO IN (SELECT DISTINCT DOC_NO FROM PRODUCTION.FELT_SALES_RETURNS_DETAIL WHERE PIECE_NO ='"+ pieceno +"') ";
        }
        
       getParent().getParent().getParent().getParent().show(false);
    }//GEN-LAST:event_cmdFindActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtgroupcode;
    private javax.swing.JTextField txtpartycode;
    private javax.swing.JTextField txtpieceno;
    // End of variables declaration//GEN-END:variables
    
}
