/*
 * frmItemMapping.java
 *
 * Created on June 23, 2005, 12:20 PM
 */

package EITLERP.MIS;

/**
 *
 * @author  root
 */
import EITLERP.Stores.*;
import EITLERP.Purchase.*;
import javax.swing.*;
import java.awt.*;
import java.util.*;
import EITLERP.*;
import java.sql.*;


public class frmExcessMIR extends javax.swing.JApplet {
    
    private EITLTableModel DataModel=new EITLTableModel();
    
    /** Initializes the applet frmItemMapping */
    public void init() {
        setSize(665,440);
        initComponents();
        FormatGrid();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        cmdGenerate = new javax.swing.JButton();
        opgApproved = new javax.swing.JRadioButton();
        opgUnapproved = new javax.swing.JRadioButton();
        opgBoth = new javax.swing.JRadioButton();
        
        
        getContentPane().setLayout(null);
        
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        
        jPanel1.setLayout(null);
        
        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setText("LIST OF MIR HAVING EXCESS QTY ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(7, 8, 229, 15);
        
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 2, 679, 32);
        
        Table.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
        ));
        jScrollPane1.setViewportView(Table);
        
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(5, 133, 643, 266);
        
        cmdGenerate.setText("Generate the list");
        cmdGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGenerateActionPerformed(evt);
            }
        });
        
        getContentPane().add(cmdGenerate);
        cmdGenerate.setBounds(10, 96, 187, 25);
        
        opgApproved.setText("Approved MIR");
        buttonGroup1.add(opgApproved);
        getContentPane().add(opgApproved);
        opgApproved.setBounds(269, 46, 114, 23);
        
        opgUnapproved.setSelected(true);
        opgUnapproved.setText("Unapproved MIR");
        buttonGroup1.add(opgUnapproved);
        getContentPane().add(opgUnapproved);
        opgUnapproved.setBounds(269, 70, 169, 23);
        
        opgBoth.setText("Both");
        buttonGroup1.add(opgBoth);
        getContentPane().add(opgBoth);
        opgBoth.setBounds(269, 96, 83, 23);
        
    }//GEN-END:initComponents

    private void cmdGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGenerateActionPerformed
        // TODO add your handling code here:
        GenerateGrid();
    }//GEN-LAST:event_cmdGenerateActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked
                    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdGenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opgApproved;
    private javax.swing.JRadioButton opgBoth;
    private javax.swing.JRadioButton opgUnapproved;
    // End of variables declaration//GEN-END:variables
    
    private void FormatGrid() {
        DataModel=new EITLTableModel();
        
        Table.removeAll();
        
        Table.setModel(DataModel);
        Table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        DataModel.addColumn("Sr."); //0
        DataModel.addColumn("MIR No."); //1
        DataModel.addColumn("Date"); //2
        DataModel.addColumn("Item Code"); //3
        DataModel.addColumn("Item Name"); //3
        DataModel.addColumn("Received Qty");//4
        DataModel.addColumn("Excess Qty");//5
        DataModel.addColumn("PO No.");//6
                
        DataModel.SetNumeric(0,true);
        DataModel.SetNumeric(4,true);
        DataModel.SetNumeric(5,true);
        
        DataModel.TableReadOnly(true);
    }
    
    
    private void GenerateGrid() {
        
        String strSQL;
        ResultSet rsTmp=null;
        Connection tmpConn=null;
        Statement stTmp=null;
        int cnt=0;
        
        FormatGrid();

        try
        {
        strSQL="SELECT A.MIR_NO,DATE_FORMAT(A.MIR_DATE,'%d/%m/%Y') AS MIR_DATE,B.ITEM_ID,C.ITEM_DESCRIPTION AS ITEM_NAME,B.RECEIVED_QTY,B.EXCESS_QTY,B.PO_NO FROM D_INV_MIR_HEADER A, D_INV_MIR_DETAIL B, D_INV_ITEM_MASTER C WHERE A.MIR_NO=B.MIR_NO AND B.ITEM_ID=C.ITEM_ID AND B.EXCESS_QTY>0 AND A.COMPANY_ID="+EITLERPGLOBAL.gCompanyID+" ";
        
        if(opgApproved.isSelected())
        {
          strSQL=strSQL+" AND A.APPROVED=1 ";  
        }
        
        if(opgUnapproved.isSelected())
        {
          strSQL=strSQL+" AND A.APPROVED=0";  
        }
        
        tmpConn=data.getConn();
        stTmp=tmpConn.createStatement();
        rsTmp=stTmp.executeQuery(strSQL);
        rsTmp.first();
              
         while(!rsTmp.isAfterLast())
         {
            cnt++;
            Object[] rowData=new Object[8];
            rowData[0]=Integer.toString(cnt);
            rowData[1]=rsTmp.getString("MIR_NO");
            rowData[2]=rsTmp.getString("MIR_DATE");
            rowData[3]=rsTmp.getString("ITEM_ID");
            rowData[4]=rsTmp.getString("ITEM_NAME");
            rowData[5]=Double.toString(rsTmp.getDouble("RECEIVED_QTY"));
            rowData[6]=Double.toString(rsTmp.getDouble("EXCESS_QTY"));
            rowData[7]=rsTmp.getString("PO_NO");
            
            DataModel.addRow(rowData);
             
            rsTmp.next();
         }
        
        }
        catch(Exception e)
        {
            
        }
    }

    
    
}
