/*
 * frmBalance.java
 *
 * Created on August 14, 2007, 3:43 PM
 */

package EITLERP.Finance.ReportsUI;

/**
 *
 * @author  root
 */
import EITLERP.*;
import EITLERP.Finance.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;
import javax.swing.event.*;
import javax.swing.text.*;
import java.util.*;
import java.math.BigDecimal;

public class frmBalance extends javax.swing.JApplet {
    
    private EITLTableModel DataModel=new EITLTableModel();
    
    /** Initializes the applet frmBalance */
    public void init() {
        setSize(520,450);
        initComponents();
        txtDate.setText(EITLERPGLOBAL.getCurrentDate());
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        lblTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblBalance = new javax.swing.JLabel();
        lblBalanceAll = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMainAccountCode = new javax.swing.JTextField();
        txtSubAccountCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        cmdShow = new javax.swing.JButton();
        lblMainAccountName = new javax.swing.JLabel();
        lblSubAccountName = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(0, 153, 153));
        lblTitle.setForeground(java.awt.Color.white);
        lblTitle.setText(" ACCOUNT BALANCE INQUIRY");
        lblTitle.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle);
        lblTitle.setBounds(0, 1, 666, 25);

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        lblBalance.setFont(new java.awt.Font("Dialog", 1, 18));
        lblBalance.setForeground(new java.awt.Color(102, 102, 255));
        lblBalance.setText("Balance");
        jPanel1.add(lblBalance);
        lblBalance.setBounds(15, 22, 220, 20);

        lblBalanceAll.setFont(new java.awt.Font("Dialog", 1, 18));
        lblBalanceAll.setForeground(new java.awt.Color(153, 153, 153));
        lblBalanceAll.setText("Balance");
        jPanel1.add(lblBalanceAll);
        lblBalanceAll.setBounds(14, 66, 220, 20);

        jTabbedPane1.addTab("Balance", jPanel1);

        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(6, 12, 470, 130);

        jTabbedPane1.addTab("Balance Bifurcation", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(3, 200, 490, 200);

        jLabel1.setText("Main Account Code");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(5, 39, 130, 15);

        jLabel2.setText("Sub Account Code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 87, 120, 15);

        txtMainAccountCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMainAccountCodeFocusLost(evt);
            }
        });
        txtMainAccountCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMainAccountCodeKeyPressed(evt);
            }
        });

        getContentPane().add(txtMainAccountCode);
        txtMainAccountCode.setBounds(136, 38, 130, 19);

        txtSubAccountCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubAccountCodeFocusLost(evt);
            }
        });
        txtSubAccountCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSubAccountCodeKeyPressed(evt);
            }
        });

        getContentPane().add(txtSubAccountCode);
        txtSubAccountCode.setBounds(136, 86, 130, 19);

        jLabel3.setText("As on Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(52, 149, 80, 15);

        getContentPane().add(txtDate);
        txtDate.setBounds(136, 146, 130, 19);

        cmdShow.setText("Show");
        cmdShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdShowActionPerformed(evt);
            }
        });

        getContentPane().add(cmdShow);
        cmdShow.setBounds(276, 146, 88, 20);

        lblMainAccountName.setText("...");
        getContentPane().add(lblMainAccountName);
        lblMainAccountName.setBounds(136, 63, 350, 15);

        lblSubAccountName.setText("...");
        getContentPane().add(lblSubAccountName);
        lblSubAccountName.setBounds(136, 114, 350, 15);

    }//GEN-END:initComponents

    private void txtMainAccountCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMainAccountCodeFocusLost
        // TODO add your handling code here:
        lblMainAccountName.setText(clsAccount.getAccountName(txtMainAccountCode.getText(),""));
    }//GEN-LAST:event_txtMainAccountCodeFocusLost

    private void txtSubAccountCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAccountCodeFocusLost
        // TODO add your handling code here:
    lblSubAccountName.setText(clsPartyMaster.getAccountName(txtMainAccountCode.getText(),txtSubAccountCode.getText()));        
    }//GEN-LAST:event_txtSubAccountCodeFocusLost
    
    private void txtSubAccountCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubAccountCodeKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==112) {
            
            LOV aList=new LOV();
            
            aList.SQL="SELECT PARTY_CODE,PARTY_NAME FROM D_FIN_PARTY_MASTER WHERE APPROVED=1 ORDER BY PARTY_NAME";
            aList.ReturnCol=1;
            aList.ShowReturnCol=true;
            aList.DefaultSearchOn=2;
            aList.UseSpecifiedConn=true;
            aList.dbURL=FinanceGlobal.FinURL;
            
            if(aList.ShowLOV()) {
                txtSubAccountCode.setText(aList.ReturnVal);
                lblSubAccountName.setText(clsPartyMaster.getAccountName(txtMainAccountCode.getText(),aList.ReturnVal));
            }
            
        }
    }//GEN-LAST:event_txtSubAccountCodeKeyPressed
    
    private void txtMainAccountCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMainAccountCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==112) {
            LOV aList=new LOV();
            
            aList.SQL="SELECT MAIN_ACCOUNT_CODE,ACCOUNT_NAME FROM D_FIN_GL WHERE APPROVED=1 ORDER BY ACCOUNT_NAME";
            aList.ReturnCol=1;
            aList.ShowReturnCol=true;
            aList.DefaultSearchOn=2;
            aList.UseSpecifiedConn=true;
            aList.dbURL=FinanceGlobal.FinURL;
            
            if(aList.ShowLOV()) {
                txtMainAccountCode.setText(aList.ReturnVal);
                lblMainAccountName.setText(clsAccount.getAccountName(aList.ReturnVal,""));
            }
            
        }
    }//GEN-LAST:event_txtMainAccountCodeKeyPressed
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked
    
    private void cmdShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdShowActionPerformed
        // TODO add your handling code here:
        DisplaySingleBalance();
        DisplayBifurcation();
    }//GEN-LAST:event_cmdShowActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton cmdShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceAll;
    private javax.swing.JLabel lblMainAccountName;
    private javax.swing.JLabel lblSubAccountName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMainAccountCode;
    private javax.swing.JTextField txtSubAccountCode;
    // End of variables declaration//GEN-END:variables
    
    private void DisplaySingleBalance() {
        
        double Closing=clsAccount.getClosingBalance(txtMainAccountCode.getText(), txtSubAccountCode.getText(), EITLERPGLOBAL.formatDateDB(txtDate.getText()),true);
        
        if(Closing<0) {
            lblBalance.setText(new BigDecimal(Math.abs(Closing)).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Cr.");
            
        }
        else {
            lblBalance.setText(new BigDecimal(Closing).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Dr.");
        }
        
        Closing=clsAccount.getAvailableClosingBalance(txtMainAccountCode.getText(), txtSubAccountCode.getText(), EITLERPGLOBAL.formatDateDB(txtDate.getText()));
        
        if(Closing<0) {
            lblBalanceAll.setText(new BigDecimal(Math.abs(Closing)).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Cr.");
        }
        else {
            lblBalanceAll.setText(new BigDecimal(Closing).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Dr.");
        }
        
    }
    
    private void DisplayBifurcation() {
        
        double Balance=0;
        
        try {
            
            HashMap balance =clsAccount.getClosingBalanceBifurcation(txtMainAccountCode.getText(), txtSubAccountCode.getText(), EITLERPGLOBAL.formatDateDB(txtDate.getText()));
            
            FormatGrid();
            
            for(int i=1;i<=balance.size();i++) {
                
                
                clsPartyMaster objBalance=(clsPartyMaster)balance.get(Integer.toString(i));
                Object[] rowData=new Object[5];
                
                rowData[0]=objBalance.getAttribute("MAIN_ACCOUNT_CODE").getString();
                rowData[1]=objBalance.getAttribute("SUB_ACCOUNT_CODE").getString();
                rowData[2]=objBalance.getAttribute("ACCOUNT_NAME").getString();
                
                Balance=objBalance.getAttribute("BALANCE").getDouble();
                
                if(Balance<0) {
                    rowData[3]=new BigDecimal(Math.abs(Balance)).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Cr.";
                }
                else {
                    rowData[3]=new BigDecimal(Math.abs(Balance)).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Dr.";
                }

                Balance=objBalance.getAttribute("BALANCE_ALL").getDouble();
                
                if(Balance<0) {
                    rowData[4]=new BigDecimal(Math.abs(Balance)).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Cr.";
                }
                else {
                    rowData[4]=new BigDecimal(Math.abs(Balance)).setScale(2,BigDecimal.ROUND_HALF_UP).toString()+" Dr.";
                }
                
                DataModel.addRow(rowData);
            }
            
            
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    
    private void FormatGrid() {
        try {
            
            DataModel=new EITLTableModel();
            Table.removeAll();
            
            Table.setModel(DataModel);
            TableColumnModel ColModel=Table.getColumnModel();
            Table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            DataModel.addColumn("Main Code"); //0 - Read Only
            DataModel.addColumn("Sub Code"); //1
            DataModel.addColumn("A/c Name"); //2 //Read Only
            DataModel.addColumn("Balance");//3
            DataModel.addColumn("Balance (All)");//4
            
            DataModel.SetVariable(0,"MAIN_ACCOUNT_CODE"); //0 - Read Only
            DataModel.SetVariable(1,"SUB_ACCOUNT_CODE"); //1
            DataModel.SetVariable(2,"ACCOUNT_NAME"); //2 //Read Only
            DataModel.SetVariable(3,"BALANCE"); //2 //Read Only
            DataModel.SetVariable(4,"BALANCE"); //2 //Read Only
            
            DataModel.TableReadOnly(true);
            
        }
        catch(Exception e) {
            
        }
    }
    
}
